#ifndef __DATALIMITS_H__
#define __DATALIMITS_H__

#define MAXHEADER 24
#define MAXSTOCKCODE 8
#define MAXSTOCKNAME 64
#define MAXALIAS 24
#define MAXNAME 64
#define MAXZIP 10
#define MAXCITY 48
#define MAXSTREET 48
#define MAXPOBOX 10
#define MAXPHONE 12
#define MAXPLATE 16
#define MAXEXTRAS 255
#define MAXBANKNAME 50
#define MAXISSUEPOST 50
#define MAXBIRTHPLACE 32
#define MAXCUSTOMNUMBER 15
#define MAXEXPENSECATEGORYNAME 16
#define MAXEXPENSECATEGORYDESC 100
#define MAXCELLPHONE 16
#define MAXEMAILADDRESS 64
#define MAXPASSIMGLBL 24
#define MAXWETLICENCENO 12
#define MAXAGENTCODE 8
#define MAXAGENTNAME 64
#define MAXAGENTPLATENO 16
#define MAXHEALTHCERTNO 16



#endif
