//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by cattlebasefrm.rc
//
#define VERSION_BASEYEAR                0
#define VERSION_MINOR                   0
#define VERSION_BUILDNO                 0
#define VS_VERSION_INFO                 1
#define VERSION_MAJOR                   5
#define IDR_MAINFRAME                   100
#define IDD_ADDDOC                      101
#define IDD_ADDITEM                     102
#define IDD_ADDUSER                     103
#define IDD_ALLINVOPT                   104
#define IDD_ALLINVOPT5                  105
#define IDD_ARCHIVE                     106
#define IDD_ASKDOCNO                    107
#define IDD_BACKUP                      108
#define IDD_BUSY_DLG                    109
#define IDD_CHOOSECOWBYEANDLG           110
#define IDD_COW                         111
#define IDD_DEZYNFDOCOPT                112
#define IDD_ABOUTBOX                    113
#define IDD_DIFFMERGEDATA               114
#define IDD_DOCDLG                      115
#define IDD_EDITBOXDLG                  116
#define IDD_FINDCOW                     117
#define IDD_FINDDOC                     118
#define IDD_FINDHENT                    119
#define IDD_FINDINVOICE                 120
#define IDD_COMPANY                     121
#define IDD_HENT                        122
#define IDD_IMPORTEXPORTOPT             123
#define IDD_INDOC                       124
#define IDD_INFOTEXTBOX                 125
#define IDD_INVOICE                     127
#define IDD_BIGINVOICE                  127
#define IDD_INVOICEVIEW                 128
#define IDD_ISSUEDLG                    129
#define IDD_LISTSELECTDLG               130
#define IDD_LOGIN                       131
#define IDD_MAINOPT                     132
#define IDD_MERGEDLG                    133
#define IDD_STOCKS                      135
#define IDD_LISTEDITDLG                 135
#define IDD_OCROPT                      136
#define IDD_RECOGNITIONDATAOPTS         136
#define IDD_OCRPASS_DIALOG              137
#define IDD_PASSIMGDBMNGMNT             138
#define IDD_PASSIMGVIEWDLG              139
#define IDD_PASSSEARCHDLG               140
#define IDD_PRESEL                      141
#define IDD_PRINT                       142
#define IDD_PRINTOPT                    143
#define IDD_PROP                        144
#define IDD_PROPERTIES                  145
#define IDD_HERDBOOKOPTDLG              146
#define IDD_REJECTEDBASE                147
#define IDD_RULEPART                    148
#define IDD_RULES                       149
#define IDD_SEARCH                      151
#define IDD_STATS                       152
#define IDD_SYNCDLG                     154
#define IDD_SYNCREJECTED                155
#define IDD_TASKPROGRESS_DLG            156
#define IDD_TIMES                       157
#define IDD_USERS                       158
#define IDD_WELCOME                     159
#define IDD_WETBOOKOPTDLG               160
#define IDD_WZPZOPT                     161
#define IDD_ZGLOSZENIEOPTDLG            162
#define IDI_BAD                         163
#define IDI_GOOD                        164
#define IDI_HENTBLUE                    165
#define IDI_HENTGREEN                   166
#define IDI_HENTRED                     167
#define IDB_ADDCOW                      168
#define IDB_BARCODE                     169
#define IDB_BITMAP3                     170
#define IDB_BLUEMINUS                   171
#define IDB_BOOKS                       172
#define IDB_CANCEL                      173
#define IDB_CASH                        176
#define IDB_CHECKBOX                    177
#define IDB_COLLECTOR                   179
#define IDB_DOSCAN                      180
#define IDB_DROPBOX                     181
#define IDB_FACE                        182
#define IDB_FLAGS                       183
#define IDB_GOPRINT                     184
#define IDB_HENTADD                     185
#define IDB_INDOCADD                    186
#define IDB_LOGOCOW                     187
#define IDB_MAGICSELECT                 188
#define IDB_PRINTOPT                    189
#define IDB_QUESTION                    190
#define IDB_REDPLUS                     191
#define IDB_SCANADDCOW                  192
#define IDB_SCANNER                     193
#define IDB_SCANOPT                     194
#define IDB_SEARCH                      195
#define IDB_SELECTICON                  196
#define IDB_SHEEPA                      197
#define IDB_SORTARROWS                  198
#define IDB_SYNCGETDATA                 199
#define IDB_SYNCSENDDATA                200
#define IDB_TERMSTAR                    201
#define IDB_TRASH                       202
#define IDB_WELCOME                     203
#define IDR_CATTLETYPE                  204
#define IDR_COMPUTEMENU                 205
#define IDR_COUNTRYEDITMENU             206
#define IDR_COWLISTPOPMENU              207
#define IDR_DLGACCEL                    208
#define IDR_FASTSELECT_MENU             209
#define IDR_FASTSELECT_TOOLBAR          210
#define IDR_GRIDPOPMENU                 211
#define IDR_HENTCOMBOMENU               212
#define IDR_HENTSYNCIT_YN_MENU          213
#define IDR_TOOLBAR_GRIDCTRL            214
#define IDR_STATUSBAR                   215
#define IDR_MOUNTMENU                   216
#define IDR_PRICELISTMENU               217
#define IDR_SHOWMENU                    218
#define IDR_SUMMENU                     219
#define IDR_TOOLBAR_BIG_TRUE_COLOR      220
#define IDR_TOOLBAR_BIG_TRUE_COLOR2     221
#define IDR_TOOLBAR_BIG_TRUE_COLOR3     222
#define IDS_ACCEPTINVOICE               223
#define IDS_ADDCOWBTNCAPTION            224
#define IDS_ADDEDITSTOCK                225
#define IDS_ALLDOCSREJECTED             226
#define IDS_ARCHIVEWILDCARD             227
#define IDS_ASKADDBADCKSUMEANS          228
#define IDS_ASKBEFOREPASSBDFILEMOVE     229
#define IDS_ASKCOMMITSYNC               230
#define IDS_ASKCOWDEL                   231
#define IDS_ASKEMPTYPASSNO              232
#define IDS_ASKEXIT                     233
#define IDS_ASKEXPORTRR                 234
#define IDS_ASKFORUPDATE                235
#define IDS_ASKHENTMERGE                236
#define IDS_ASKINSERTINTODB             237
#define IDS_ASKLOADPRIMARYBASE          238
#define IDS_ASKMARKPAID                 239
#define IDS_ASKPRINTTRANS               240
#define IDS_ASKRESTOREPASSDBFILE        241
#define IDS_ASKSTOCKMERGETEXT           242
#define IDS_BACKUPTIME1                 243
#define IDS_BACKUPTIME14                244
#define IDS_BACKUPTIME183               245
#define IDS_BACKUPTIME3                 246
#define IDS_BACKUPTIME30                247
#define IDS_BACKUPTIME365               248
#define IDS_BACKUPTIME61                249
#define IDS_BACKUPTIME7                 250
#define IDS_BACKUPWILDCARD              251
#define IDS_BADCKSUMEANS                252
#define IDS_BADCTRLDIGIT                253
#define IDS_BADDATEFORMAT               254
#define IDS_BADNUMBERFMT                255
#define IDS_BADPRICE                    256
#define IDS_BIRTHFIELDNAME              257
#define IDS_BOTTOMSTATTEXT              258
#define IDS_BTNADD                      259
#define IDS_BTNEDIT                     260
#define IDS_BTNINSERT                   261
#define IDS_BUYCAPTION                  262
#define IDS_BUYSTOCKTOOLTIP             263
#define IDS_BUYWEIGHTTOOLTIP            264
#define IDS_CANDELCURUSER               265
#define IDS_CANEEDITCOWHERE             266
#define IDS_CANNOTSHOWFSTOWNR           267
#define IDS_CANTCREATEPASSDB            268
#define IDS_CANTDELALLCOWS              269
#define IDS_ERRUPDATINGCOWWHENDELINV    270
#define IDS_CANTLOADDB                  271
#define IDS_CANTMAKEINVOICE             272
#define IDS_CANTMAKERRINV               273
#define IDS_CANTMAKEVATINVOICE          274
#define IDS_CANTOPENOUTPUTFILE          275
#define IDS_CANTOPENPASSDB              276
#define IDS_CANTRESTOREBACKUP           277
#define IDS_CHOOSEBASEDIR               278
#define IDS_CHOOSEDESTDIR               279
#define IDS_CHOOSEDOCTOADD              280
#define IDS_CLOSEHIDDENDLGS             281
#define IDS_COMPUTE                     282
#define IDS_CONFHENTDELETE              283
#define IDS_CONFIRMCOWDEL               284
#define IDS_CONFIRMDOCDEL               285
#define IDS_CONFIRMINVDEL               286
#define IDS_COWCOUNT                    287
#define IDS_COWSHAVEDIFFOWNR            288
#define IDS_COWSHAVERRINV               289
#define IDS_COWSLEFT                    290
#define IDS_COWSNOTINSAMEINDOC          291
#define IDS_CUSTOMCOLORS                292
#define IDS_DELOUTDOCCOWAGAINNOTSOLD    293
#define IDS_DETAILSHIDE                 294
#define IDS_DETAILSSHOW                 295
#define IDS_DOARCHIVEWARN               296
#define IDS_DOCNAME_DEZYNFPZ            297
#define IDS_DOCNAME_DEZYNFWZ            298
#define IDS_DOCNAME_FAKRR_WEIGHT        299
#define IDS_DOCNAME_FAKRR3_WEIGHT       300
#define IDS_DOCNAME_VATINVOICE          301
#define IDS_DOCNAME_VATINVGRPPIECE      302
#define IDS_DOCNAME_VATINVGRPWEIGHT     303
#define IDS_DOCNAME_VATINVCOMPACTPIECE  304
#define IDS_DOCNAME_IDPZ                305
#define IDS_DOCNAME_INDOCS              306
#define IDS_DOCNAME_OUTDOCS             307
#define IDS_DOCNAME_PASS                308
#define IDS_DOCNAME_PRZELEW             309
#define IDS_DOCNAME_PZZGL30DO           310
#define IDS_DOCNAME_PZZGL60DO           311
#define IDS_DOCNAME_PZZGL16DO           312
#define IDS_DOCNAME_PZZGLPOCZTDO        313
#define IDS_DOCNAME_RAPORT              314
#define IDS_DOCNAME_SOKOLOW             315
#define IDS_DOCNAME_SPECFAKWEW          316
#define IDS_DOCNAME_SWIADZDR            317
#define IDS_DOCNAME_WETBOOK             318
#define IDS_DOCNAME_WZZGL30Z            319
#define IDS_DOCNAME_WZZGL60Z            320
#define IDS_DOCNAME_WZZGLPOCZTZ         321
#define IDS_DOCNAME_WZZGL16Z            322
#define IDS_DOCNAME_ZBRPOLPRZEL         323
#define IDS_DOCNAME_ZESTFAKKUPNA        324
#define IDS_DOCNAME_ZESTFAKSPRZ         325
#define IDS_DOCOPTFMT                   326
#define IDS_DOCTEMPLATEMISSING          327
#define IDS_DUPLBASENO                  328
#define IDS_DUPLEANINDB                 329
#define IDS_DUPLEANNOTSOLD              330
#define IDS_DUPLEANONLIST               331
#define IDS_DUPLLISTNO                  332
#define IDS_DUPLPASSNOINDB              333
#define IDS_DUPLPASSNOONLIST            334
#define IDS_DUPLSTOCKCODE               335
#define IDS_DYMOINITFAILD               336
#define IDS_DYMOLWLTEMPLNOTFOUND        337
#define IDS_DYMOMENU                    338
#define IDS_EANSNOTFOUND                339
#define IDS_EANTOOLTIPTEXT              340
#define IDS_EANTOOLTIPTITLE             341
#define IDS_EDITCOWCAPTION              342
#define IDS_EDITINVCAPTION              343
#define IDS_EDITRULECAPTION             344
#define IDS_EERCANTMOVENEWCOW           345
#define IDS_EMPTYCOMPANYFARMNO          346
#define IDS_EMPTYCOWLIST                347
#define IDS_EMPTYPRICE                  348
#define IDS_EMPTYRULENAME               349
#define IDS_ERRADDINGCOWTOINDOC         350
#define IDS_ERRADDINGCOWTOOUTDOC        351
#define IDS_ERRASSIGNINGCOWS            352
#define IDS_ERRBADDATE                  353
#define IDS_ERRCANTCOPYTMP              354
#define IDS_ERRCANTDELALLDOCS           355
#define IDS_ERRCANTDELCOW               356
#define IDS_ERRCANTDELDOC               357
#define IDS_ERRCANTDELINV               358
#define IDS_ERRCANTDELSTOCK             359
#define IDS_ERRCANTDELUSR               360
#define IDS_ERRCANTDROPDOCS             361
#define IDS_ERRCANTEDITCOW              362
#define IDS_ERRCANTEDITDOC              363
#define IDS_ERRCANTLOADFIRMINFO         364
#define IDS_ERRCANTLOADUSERS            365
#define IDS_ERRCANTMOUNTPRIMARYPASSDBFILE 366
#define IDS_ERRCANTMOVETODOC            367
#define IDS_ERRCANTOPENCATTLEBASE       368
#define IDS_ERRCANTOPENFILE             369
#define IDS_ERRCFGERROR                 370
#define IDS_ERRCHOOSECOWEAN             371
#define IDS_ERRCHOOSEDIRECTORY          372
#define IDS_ERRCHOOSEDOCFONT            373
#define IDS_ERRCHOOSEMAXPASSFILESIZE    374
#define IDS_ERRCLIIDDONTMATCHLIC        375
#define IDS_ERRCOWAGEERROR              376
#define IDS_ERRDELETEINGINVOICE         377
#define IDS_ERRDELETINGCOWFROMINDOC     378
#define IDS_ERRDELETINGCOWFROMOUTDOC    379
#define IDS_ERRDELETINGRULE             380
#define IDS_ERRDOINGARCHIVE             381
#define IDS_ERRDOINGBACKUP              382
#define IDS_ERRDOINGDBCOPY              383
#define IDS_ERREDITUSR                  384
#define IDS_ERREMPTYALIAS               385
#define IDS_ERREMPTYARIMRNO             386
#define IDS_ERREMPTYCITY                387
#define IDS_ERREMPTYCOWLIST             388
#define IDS_ERREMPTYEAN                 389
#define IDS_ERREMPTYNAME                390
#define IDS_ERREMPTYPASSNO              391
#define IDS_ERREMPTYPLATENO             392
#define IDS_ERREMPTYSTREET              393
#define IDS_ERREMPTYUSERNAME            394
#define IDS_ERREMPTYZIP                 395
#define IDS_ERRFAILTOMARKPAID           396
#define IDS_ERRFILEALREADYMOUNTED       397
#define IDS_ERRFILLFARMNO               398
#define IDS_ERRFILLFIRMNAME             399
#define IDS_ERRHASINVOICE               400
#define IDS_ERRINDOCUPDATECOWNOTFOUND   401
#define IDS_ERRINSERTINGCOW             402
#define IDS_ERRINSERTINGDOC             403
#define IDS_ERRINSERTINGHENT            404
#define IDS_ERRINSERTINGINVOICE         405
#define IDS_ERRINSERTINGRULE            406
#define IDS_ERRINSERTINGSTOCK           407
#define IDS_ERRINSLONLYCOW              408
#define IDS_ERRLICFILECORUPTED          409
#define IDS_ERRLICWRONGVER              410
#define IDS_ERRMANUALINPUTEAHCHNG       411
#define IDS_ERRINVALIDINVENTRIES        412
#define IDS_ERRMISSINGCLIENTID          413
#define IDS_ERRMUTEX                    414
#define IDS_ERRNEEDADMIN                415
#define IDS_ERRNODELIVER                416
#define IDS_ERRNODOCDATE                417
#define IDS_ERRNODOCTODEL               418
#define IDS_ERRNOGTLTBUYCHOSEN          419
#define IDS_ERRNOGTLTSELLCHOSEN         420
#define IDS_ERRNOHENT                   421
#define IDS_ERRNOHKEY                   422
#define IDS_ERRNOINREASON               423
#define IDS_ERRNOINVDATE                424
#define IDS_ERRNOKEYSERV                425
#define IDS_ERRNOLICENCE                426
#define IDS_ERRNOLICFILE                427
#define IDS_ERRNOLOADDATE               428
#define IDS_ERRNOLOGGEDUSER             429
#define IDS_ERRNOOUTLOADDATE            430
#define IDS_ERRNOOUTREASON              431
#define IDS_ERRNOPASSDBFILE             432
#define IDS_ERRNOPAYWAY                 433
#define IDS_ERRNOPRINTDATA              434
#define IDS_ERRNOSELBACKUP              435
#define IDS_ERRNOSTOCKCODE              436
#define IDS_ERRNOWRONGKEYVER            437
#define IDS_ERROCRNOHENT                438
#define IDS_ERROCRNOSTOCK               439
#define IDS_ERRONLYCOW                  440
#define IDS_ERROPENINGDB                441
#define IDS_ERRORCANTOPENINPUTFILE      442
#define IDS_ERRORDEVICENOTREADY         443
#define IDS_ERRORGETOPTION              444
#define IDS_ERRORREADING                445
#define IDS_ERRORSETOPTION              446
#define IDS_ERRRELOADCONTINUE           447
#define IDS_ERRRELOADNOCONTINUE         448
#define IDS_ERRREQWEIGHT                449
#define IDS_ERRRESTOREBACKUP            450
#define IDS_ERRSELDOCTYPE               451
#define IDS_ERRSELHENT                  452
#define IDS_ERRSELHTYPE                 453
#define IDS_ERRSELRESOLUTION            454
#define IDS_ERRSELSTOCK                 455
#define IDS_ERRSELUSER                  456
#define IDS_ERRSETTOTALPRICE            457
#define IDS_GOTERRORSYNCINGINDOCSCANTCONTINUE 458
#define IDS_GOTERRORSYNCINGOUTDOCSCANTCONTINUE 459
#define IDS_ERRUPDATEINGCOW             460
#define IDS_ERRUPDATEINGDOC             461
#define IDS_ERRUPDATEINGCOWININDOC      462
#define IDS_ERRUPDATINGCOWDELOUTDOC     463
#define IDS_ERRUPDATINGCOWPASSIMG       464
#define IDS_ERRUPDATINGCOWPRICE         465
#define IDS_ERRUPDATINGDOCSFORINV       466
#define IDS_ERRUPDATINGDOCWHENDELINV    467
#define IDS_ERRUPDATINGFIRMINFO         468
#define IDS_ERRUPDATINGHENT             469
#define IDS_ERRUPDATINGINVOICE          470
#define IDS_ERRUPDATINGRULE             471
#define IDS_ERRUPDATINGSTOCK            472
#define IDS_ERRUSERNAME                 473
#define IDS_ERRUSRADDEMPTYFIELDS        474
#define IDS_ERRUSRADDPASSNOTMATCHING    475
#define IDS_ERRWHILEADDINGDOCSTOINV     476
#define IDS_ERRWHILECHNGINGOUTGRP       477
#define IDS_ERRWHILEDELETINGCOWS        478
#define IDS_ERRWHILEDELETINGDOC         479
#define IDS_ERRWHILEDELETINGDOCSFROMINV 480
#define IDS_ERRWHILEDELETINGHENT        481
#define IDS_ERRWHILELOADINGUSERS        482
#define IDS_ERRWRONGFIRMINFO            483
#define IDS_ERRWRONGHKEY                484
#define IDS_ERRWRONGPASS                485
#define IDS_ERRWRONGPASSNOVAL           486
#define IDS_ERRWRONGUSRNAME             487
#define IDS_EXCELEXPORT                 488
#define IDS_EXPORTDOCS                  489
#define IDS_EXPORTHENTHASEMPTYFARMNO    490
#define IDS_EXPORTTOFILE                491
#define IDS_FAILEDTOMARKPAIDARRAY       492
#define IDS_FARMNOTOOLTIPTEXT           493
#define IDS_FASTCOWSEARCH               494
#define IDS_FASTSELECT                  495
#define IDS_FEATUREDISABLED             496
#define IDS_FIRSTLOGIN                  497
#define IDS_FLOATFMT                    498
#define IDS_FOUNDCAPTION                499
#define IDS_FROMALLCOWSGRID             500
#define IDS_FSTOWNRADRFIELDNAME         501
#define IDS_GRIDNAME_ALLCOWS            502
#define IDS_GRIDNAME_BUYINVS            503
#define IDS_GRIDNAME_COMPANYHENTS       504
#define IDS_GRIDNAME_FARMERSHENTS       505
#define IDS_GRIDNAME_HENTS              506
#define IDS_GRIDNAME_INCOWS             507
#define IDS_GRIDNAME_INDOCS             508
#define IDS_GRIDNAME_OUTDOCS            509
#define IDS_GRIDNAME_RRINVS             510
#define IDS_GRIDNAME_SELLINVS           511
#define IDS_GT                          512
#define IDS_HEADERALIAS                 513
#define IDS_HEADERAMOUNT                514
#define IDS_HEADERARIMRNO               515
#define IDS_HEADERBIRTHDATE             516
#define IDS_HEADERBOUGHTFOR             517
#define IDS_HEADERBRUTTO                518
#define IDS_HEADERBRUTTOPRICE           519
#define IDS_HEADERBUYER                 520
#define IDS_HEADERBUYPRICE              521
#define IDS_HEADERBUYSTOCK              522
#define IDS_HEADERBUYWEIGHT             523
#define IDS_HEADERCITY                  524
#define IDS_HEADERCORRECT               525
#define IDS_HEADERCOWNO                 526
#define IDS_HEADERCUSTNO                527
#define IDS_HEADERCUSTOMCOUNT           528
#define IDS_HEADERDELIVER               529
#define IDS_HEADERDOC                   530
#define IDS_HEADERDOCDATE               531
#define IDS_HEADERDOCNO                 532
#define IDS_HEADERDOMOUNT               533
#define IDS_HEADEREAN                   534
#define IDS_HEADEREMPTY                 535
#define IDS_HEADEREXTRAS                536
#define IDS_HEADERFIELDNAME             537
#define IDS_HEADERFIELDONOFF            538
#define IDS_HEADERFIRSTSTOCK            539
#define IDS_HEADERFORENAME              540
#define IDS_HEADERFSTOWNER              541
#define IDS_HEADERHASTERM               542
#define IDS_HEADERHENT                  543
#define IDS_HEADERHENTTYPE              544
#define IDS_HEADERINDATE                545
#define IDS_HEADERINDOCNO               546
#define IDS_HEADERINDX                  547
#define IDS_HEADERINOUTDATE             548
#define IDS_HEADERINVOICE               549
#define IDS_HEADERINVSTOCK              550
#define IDS_HEADERINVWEIGHT             551
#define IDS_HEADERLASTLOGIN             552
#define IDS_HEADERLIMWEIGHT             553
#define IDS_HEADERLINK                  554
#define IDS_HEADERMOUNTSTATUS           555
#define IDS_HEADERMOUTFILEPATH          556
#define IDS_HEADERMYPERKGPRICE          557
#define IDS_HEADERMYPRICE               558
#define IDS_HEADERNAME                  559
#define IDS_HEADERNETTO                 560
#define IDS_HEADERNETTOPRICE            561
#define IDS_HEADEROTHERPRICE            562
#define IDS_HEADEROUTDATE               563
#define IDS_HEADEROUTDOCNO              564
#define IDS_HEADEROUTGRP                565
#define IDS_HEADERPAID                  566
#define IDS_HEADERPASSNO                567
#define IDS_HEADERPAYDUEDAYSDATE        568
#define IDS_HEADERPAYWAY                569
#define IDS_HEADERPLATENO               570
#define IDS_HEADERPOBOX                 571
#define IDS_HEADERPREDEFSEX             572
#define IDS_HEADERPRICEOVERXX           573
#define IDS_HEADERPRICEOVERXY           574
#define IDS_HEADERPRICEPERKG            575
#define IDS_HEADERPRICEUNDERXX          576
#define IDS_HEADERPRICEUNDERXY          577
#define IDS_HEADERPRIVS                 578
#define IDS_HEADERREASON                579
#define IDS_HEADERRRINV                 580
#define IDS_HEADERRULE                  581
#define IDS_HEADERSELLPRICE             582
#define IDS_HEADERSELLSTOCK             583
#define IDS_HEADERSELLWEIGHT            584
#define IDS_HEADERSEX                   585
#define IDS_HEADERSHORT                 586
#define IDS_HEADERSOLDFOR               587
#define IDS_HEADERSTATE                 588
#define IDS_HEADERSTOCK                 589
#define IDS_HEADERSTREET                590
#define IDS_HEADERSUBDIR                591
#define IDS_HEADERSUMPRICE              592
#define IDS_HEADERSUMWEIGHT             593
#define IDS_HEADERSURNAME               594
#define IDS_HEADERSYNCIT                595
#define IDS_HEADERTERMBUYPRICE          596
#define IDS_HEADERTERMBUYSTOCK          597
#define IDS_HEADERTERMBUYWEIGHT         598
#define IDS_HEADERTERMPRICE             599
#define IDS_HEADERTERMSELLPRICE         600
#define IDS_HEADERTERMSELLSTOCK         601
#define IDS_HEADERTERMSELLWEIGHT        602
#define IDS_HEADERTERMSTOCK             603
#define IDS_HEADERTERMWEIGHT            604
#define IDS_HEADERVALAFTERCORRECT       605
#define IDS_HEADERVAT                   606
#define IDS_HEADERVATVALUE              607
#define IDS_HEADERWEIGHT                608
#define IDS_HEADERZIP                   609
#define IDS_HEADER_COPYFROM             610
#define IDS_HEADER_COPYTO               611
#define IDS_HEADER_VALUENAME            612
#define IDS_HENTALIASMERGEISSUE         613
#define IDS_HENTASSGNEDASFSTOWNR        614
#define IDS_HENTASSIGNEDTOINDOC         615
#define IDS_HENTASSIGNEDTOOUTDOC        616
#define IDS_HENTCAPTIONEDIT             617
#define IDS_HENTCAPTIONNEW              618
#define IDS_HENTDATA_MEMBER_ACCOUNTNO   619
#define IDS_HENTDATA_MEMBER_ALIAS       620
#define IDS_HENTDATA_MEMBER_BANKNAME    621
#define IDS_HENTDATA_MEMBER_CITY        622
#define IDS_HENTDATA_MEMBER_COUNTRY     623
#define IDS_HENTDATA_MEMBER_EXTRAS      624
#define IDS_HENTDATA_MEMBER_HENTTYPE    625
#define IDS_HENTDATA_MEMBER_IDNO        626
#define IDS_HENTDATA_MEMBER_ISSUEDATE   627
#define IDS_HENTDATA_MEMBER_ISSUEPOST   628
#define IDS_HENTDATA_MEMBER_NAME        629
#define IDS_HENTDATA_MEMBER_NIP         630
#define IDS_HENTDATA_MEMBER_PESEL       631
#define IDS_HENTDATA_MEMBER_PHONE       632
#define IDS_HENTDATA_MEMBER_PLATE       633
#define IDS_HENTDATA_MEMBER_POBOX       634
#define IDS_HENTDATA_MEMBER_REGON       635
#define IDS_HENTDATA_MEMBER_STREET      636
#define IDS_HENTDATA_MEMBER_WETNO       637
#define IDS_HENTDATA_MEMBER_ZIP         638
#define IDS_HENTDIFFASK                 639
#define IDS_HENTFOUNDNOTVISIBLE         640
#define IDS_HENTMERGECONFLICT           641
#define IDS_HENTNOTFOUNDINCOMBO         642
#define IDS_HERDERAVGPRICEPERKG         644
#define IDS_IMPORTEXPORT_EXT            645
#define IDS_IMPORTEXPORT_FILEFILTER     646
#define IDS_IMPORTINDOC                 647
#define IDS_IMPORTMENUTEXT              648
#define IDS_IMPORTREJECTEDCOWLINE       649
#define IDS_IMPORTREJECTEDDOCLINE       651
#define IDS_IMPORTREJECTEDDOCS          652
#define IDS_INDOCEDIT                   653
#define IDS_INDOCNEW                    654
#define IDS_INDOCNOLABEL                655
#define IDS_INPUTFILECORRUPTED          656
#define IDS_INSERTINGPASSIMGS           657
#define IDS_INVCAPINDOC                 658
#define IDS_INVCAPOUTDOC                659
#define IDS_INVCORRECTCAPTION           660
#define IDS_INVNAVITABCOWPRICES         661
#define IDS_INVNAVITABDOCS              662
#define IDS_INVNAVITABSTAT              663
#define IDS_INVNAVITABSTOCKPRICE        664
#define IDS_INVTYPERRNAME               665
#define IDS_INVTYPEVATNAME              666
#define IDS_INVVIEWCAPTION              667
#define IDS_LASTINVOICESFMT             668
#define IDS_LEAVINGOLDPASSFILE          669
#define IDS_LOADARCHIVECAPTION          670
#define IDS_LOADBACKUPCAPTION           671
#define IDS_LOADING                     672
#define IDS_MERGING_BUYINVS             673
#define IDS_LOADING_COUNTRIES           674
#define IDS_LOADING_COWS                675
#define IDS_LOADING_HENTS               676
#define IDS_LOADING_HENTTYPES           677
#define IDS_LOADING_INDOCS              678
#define IDS_LOADING_INVOICES            679
#define IDS_LOADING_OUTDOCS             680
#define IDS_LOADING_REASONS             681
#define IDS_LOADINGCOWPRICES            682
#define IDS_LOADING_RULES               683
#define IDS_MERGING_SELLINVS            684
#define IDS_LOADING_STOCKS              685
#define IDS_LOADING_USERS               686
#define IDS_LOADSTOP                    687
#define IDS_LT                          688
#define IDS_MAINCAPTION                 689
#define IDS_MAKEINVOICE                 690
#define IDS_MAKEOUTDOCMENUTEXT          691
#define IDS_MAKERRINVOICE               692
#define IDS_MARKPAIDQUESTION            693
#define IDS_MENUTEXTCOMPUTE             694
#define IDS_MENUTEXTCOMPUTEBUYPRICE     695
#define IDS_MENUTEXTCOMPUTEMYPRICE      696
#define IDS_MENUTEXTCOMPUTESELLPRICE    697
#define IDS_MENUTEXTDROPCHNGS           698
#define IDS_MENUTEXTIGNORECKSUM         699
#define IDS_MENUTEXTSHOWOUTHENT         700
#define IDS_MERGEERRSELHENT             701
#define IDS_MONEYTRANSFER               702
#define IDS_MOTHEREANFIELDNAME          703
#define IDS_MOVECOWTOINDOCS             704
#define IDS_NEWALIAS                    705
#define IDS_NEWCOWCAPTION               706
#define IDS_NEWINVOICECAPTION           707
#define IDS_NEWRRINVOICECAPTION         708
#define IDS_NEWRULECAPTION              709
#define IDS_NOCOWSELECTED               710
#define IDS_NODOCOPTIONS                711
#define IDS_NOGRPHEADER                 712
#define IDS_NOHENTNO                    713
#define IDS_NOLASTBACKUP                714
#define IDS_NOLICENCE                   715
#define IDS_NOPASSIMAGE                 716
#define IDS_NOPRINTDOCS                 717
#define IDS_NOPRIVS                     718
#define IDS_NOROWSELECTED               719
#define IDS_NORULESELECTED              720
#define IDS_NOSCANNER                   721
#define IDS_NOTALLCOWSHAVEOWNRS         722
#define IDS_NOTASKNAME                  723
#define IDS_NOVALIDINVOICES             724
#define IDS_OCRERRANALISEERROR          725
#define IDS_OCRERREMPTYBIRTHPLACE       727
#define IDS_OCRERRNOSOURCE              728
#define IDS_OCRERROROCUR                729
#define IDS_OCRERRSKEWERR               730
#define IDS_ASKMANUALINPUT              731
#define IDS_OCRTABNAMEIMG               732
#define IDS_OCRTABNAMELIST              733
#define IDS_OFFMENUTEXT                 734
#define IDS_ONLYCOMPANIES               735
#define IDS_ONLYCOWININDOCASKDEL        736
#define IDS_ONMENUTEXT                  737
#define IDS_OPTWNDCAPTION               738
#define IDS_OTHERVERSIONFILE            739
#define IDS_OUTDOCEDIT                  740
#define IDS_OUTDOCNEW                   741
#define IDS_OUTDOC_CHNGGRP_MENUTEXT     742
#define IDS_OUTGRPSUMMARYHEADERCOL      743
#define IDS_PARTIALFARMNO               744
#define IDS_PASSDATEFIELDNAME           745
#define IDS_PASSDBFILEWASMOVED          746
#define IDS_PASSIMGNOTAVAIL             747
#define IDS_PASSNOFIELDNAME             748
#define IDS_PASSSEARCHSTATFOUND         749
#define IDS_PASSSEARCHSTATNOTFOUND      750
#define IDS_PASSSEARCHSTATNOTINGRP      751
#define IDS_PASSSEARCHSTATWAIT          752
#define IDS_PASSSTORAGEFILE             753
#define IDS_PASTDATE                    754
#define IDS_POPDOCORRECT                756
#define IDS_POPDOCORRECTEDIT            757
#define IDS_POPINVVIEW                  758
#define IDS_POPMARKPAID                 759
#define IDS_PREDEFSEXWARNING            760
#define IDS_PRICEMSG                    761
#define IDS_PROGRESS_CAPTION            762
#define IDS_REJDOCSQUESTION             763
#define IDS_REJECTEDCOWDLGCAPTION       764
#define IDS_REJECTEDRECORDS             765
#define IDS_REJECTREASON_CHNGSVIOLATEINV 766
#define IDS_REJECTREASON_DOCINNOTFOUND  767
#define IDS_REJECTREASON_DOCNO_NOT_FOUND 768
#define IDS_REJECTREASON_DOCOUTNOTFOUND 769
#define IDS_REJECTREASON_DUPLICATE      770
#define IDS_REJECTREASON_EANNOTFOUND    771
#define IDS_REJECTREASON_HENTNOTFOUND   772
#define IDS_REJECTREASON_NOCOWS         773
#define IDS_REJECTREASON_REASONNOTFOUND 774
#define IDS_REJECTREASON_STOCKNOTFOUND  775
#define IDS_REJECTREASON_TERMBUYSTOCKNOTFOUND 776
#define IDS_REJECTREASON_TERMSELLSTOCKNOTFOUND 777
#define IDS_REJECTREASON_TERSELLSTOCKNOTFOUND 778
#define IDS_REJNEWCOWSDLGCAPTION        779
#define IDS_REJNEWINDOCSDLGCAPTION      780
#define IDS_REJNEWOUTDOCSDLGCAPTION     781
#define IDS_REJUPDCOWSDLGCAPTION        782
#define IDS_REJUPDINDOCSDLGCAPTION      783
#define IDS_REJUPDOUTDOCSDLGCAPTION     784
#define IDS_REQUIREFSTOWNER             785
#define IDS_RESCHNGAFTERRESTART         786
#define IDS_RULEDETAILS                 787
#define IDS_SCANBTNCAPTION              788
#define IDS_SCANCANCELED                789
#define IDS_SCANNERNOTFOUND             790
#define IDS_SELECT                      791
#define IDS_SELECTDEFAULTSTOCK          792
#define IDS_SELLCAPTION                 793
#define IDS_SELLSTOCKTOOLTIP            794
#define IDS_SELLWEIGHTTOOLTIP           795
#define IDS_SESIONLISTDUPL              796
#define IDS_SEXFIELDNAME                797
#define IDS_SHOWHIDEMYPRICE             798
#define IDS_SHOWINGCORRECT              799
#define IDS_COWSTOCKSTAT                801
#define IDS_SHOWRELATED                 802
#define IDS_SINGLE_FILEFILTER           803
#define IDS_SORTBYLOADDATE              804
#define IDS_STOCKADDED                  805
#define IDS_STOCKFIELDNAME              806
#define IDS_SUBPRICEMSG                 807
#define IDS_SYNCABORT                   808
#define IDS_SYNCCANCEL                  809
#define IDS_SYNCDATALOCKED              810
#define IDS_SYNCEND                     811
#define IDS_SYNCERR                     812
#define IDS_SYNCFLUSH                   813
#define IDS_SYNCGETCATTLE               814
#define IDS_SYNCGETINDOCS               815
#define IDS_SYNCGETOUTDOCS              816
#define IDS_SYNCPROTERR                 817
#define IDS_SYNCSETCATTLE               818
#define IDS_SYNCSETHENTS                819
#define IDS_SYNCSETINDOCS               820
#define IDS_SYNCSETSTOCKS               821
#define IDS_SYNCSTATUS_CONNECTED        822
#define IDS_SYNCSTATUS_DISCONNECTED     823
#define IDS_TASKNAMEFINDINGDUPLICATES   824
#define IDS_TASKNAMEMERGINGCOWS         825
#define IDS_TASKNAMEMERGINGDOCS         826
#define IDS_TASKNAMEMERGINGHENTS        827
#define IDS_TASKNAMEMERGINGSTOCKS       828
#define IDS_TASKNAME_PRCSNG_RRINVS      829
#define IDS_TASKNAME_PRCSNG_DOCS        830
#define IDS_TASKNAME_PRCSNG_HENTS       831
#define IDS_TASKNAME_PRCSNG_STOCKS      832
#define IDS_TASKNAME_WRITINGTOFILE      833
#define IDS_TERMBUYPRICE                834
#define IDS_TERMBUYSTOCK                835
#define IDS_TERMBUYWEIGHT               836
#define IDS_TERMSELLPRICE               837
#define IDS_TERMSELLSTOCK               838
#define IDS_TERMSELLWEIGHT              839
#define IDS_TIPPASSIMGDBLOADED          840
#define IDS_TIPPASSIMGDBNOTLOADED       841
#define IDS_TOOOLDDATE                  842
#define IDS_TOTALTOOSMALL               843
#define IDS_UNHANDELED_EXCEPTION_MSG    844
#define IDS_UNKNERROR                   845
#define IDS_UNKNOWN_ERROR               846
#define IDS_SCANPASSMENUUPDATE          847
#define IDS_USERADD                     848
#define IDS_USEREDIT                    849
#define IDS_WAINTINGSYNCFINISH          850
#define IDS_WAITINGFORCONNECTION        851
#define IDS_WARNRESTOREBACKUP           852
#define IDS_WARNSYNCSETDATA             853
#define IDS_WELCOME_VER                 854
#define IDS_WETNOMERGEISSUE             855
#define IDS_WETONO                      856
#define IDS_YNBADCTRLDIGIT              857
#define IDS_ZEROLIMWEIGHT               858
#define IDS_FPMWMONEYTRANSFER           860
#define IDS_NOFPMWRATE                  861
#define IDS_NEWEPANSECATEGORY           862
#define IDS_HEADEREXPENSECATEGORYNAME   863
#define IDS_HEADEREXPENSECATEGORYDESC   864
#define IDS_EMPTYCATEGORYNAME           865
#define IDS_ERRINSERTINGEXPENSECATEGORY 866
#define IDS_EXPENSECATEGORYISUSED       867
#define IDI_ICON1                       868
#define IDI_EXCLAMATIONMARK             868
#define IDS_ERRDELETINGEXPENSECATEGORY  868
#define IDD_EXPENSECATEGORY             869
#define IDS_NEWEXPENSEDLGCAPTION        869
#define IDD_EXPENSE                     870
#define IDS_EXPENSETYPEINVOICE          870
#define IDS_EXPENSETYPECASH             871
#define IDS_NOEXPENSECATEGORYSELECTED   872
#define IDB_DOLAR                       873
#define IDS_NOEXPENSETYPESELECTED       873
#define IDS_NOEXPENSEINVOICEDATE        874
#define IDD_COWSTATDLG                  874
#define IDD_COWSTOCKSTATDLG             874
#define IDS_NOEXPENSEINVOICNO           875
#define IDS_ERRUPDATEINGEXPENSECATEGORY 876
#define IDI_ICON3                       876
#define IDI_NOBARCODE                   876
#define IDS_EDITEXPENSECATEGORYCAPTION  877
#define IDI_ICON2                       877
#define IDI_YESBARCODE                  877
#define IDS_EXPENSEVALUENOTCOMMITED     878
#define IDD_BARCODEENTRYDLG             878
#define IDS_EXPENSEVATNOTCOMMITED       879
#define IDD_STOCK                       879
#define IDS_EXPENSEVALUETOOSMALL        880
#define IDB_REPEAT                      880
#define IDS_HEADEREXPENSETYPE           881
#define IDB_STOCKADD                    881
#define IDS_HEADEREXPENSECATEGORY       882
#define IDS_GRIDNAME_EXPENSES           883
#define IDB_STOCKEDIT                   883
#define IDS_ERRINSERTINGEXPENSE         884
#define IDB_STOCKDEL                    884
#define IDS_LOADING_EXPENSES            885
#define IDB_BITMAP1                     885
#define IDB_STOCKOK                     885
#define IDS_LODING_EXPENSECATEGORIES    886
#define IDS_HEADEREXPENSETITLE          887
#define IDS_EDITEPANSECAPTION           888
#define IDS_ERRUPDATINGEXPENSE          889
#define IDS_ERRDELETINGEXPENSE          890
#define IDS_NOEXPENSETITLE              891
#define IDD_FINDEXPENSE                 892
#define IDS_DOCNAME_RRINVZGL30DOV2      893
#define IDB_BITMAP2                     893
#define IDB_BITMAP_SPLASH               893
#define IDS_DOCNAME_RRINVZGLPOCZTDO     894
#define IDB_PRINTER                     894
#define IDS_EXPENSEVATMISSING           895
#define IDB_PICTURE                     895
#define IDS_DYMODRIVERINIT              896
#define IDD_PRINTERTYPECHOICE           896
#define IDS_FAILDTORUNUPDATER           897
#define IDB_WINPRINTER                  897
#define IDS_CHECKINGUPDATE              898
#define IDB_DYMOPRINTER                 898
#define IDS_DOWNLOADINGURL              899
#define IDB_SEIKOPRINTER                899
#define IDS_DOCNAME_OSWIAD_FPMW         900
#define IDB_REDX                        900
#define IDS_ERRNOTACOWEAN               901
#define IDD_PRINTERDIALOG               901
#define IDS_SCANCOWEAN                  902
#define IDB_USB                         902
#define IDS_SCANFARMNODARCODE           903
#define IDB_BLUETOOTH                   903
#define IDS_ERRNOTAFARMNO               904
#define IDD_PRINTPREVIEW                904
#define IDS_GOODBC                      905
#define IDD_DIALOG1                     905
#define IDD_KEYSTATE                    905
#define IDS_NOINOUTGRP                  906
#define IDR_MENU1                       906
#define IDR_MARKPAIDMENU                906
#define IDS_ERRUPDATINGRRINVFORCOW      907
#define IDD_HERD                        907
#define IDS_ERRDELETEINGINVOICEENTRIES  908
#define IDD_CHECKLISTDLG                908
#define IDS_ERRDELETINGCOWFROMRRINV     909
#define IDD_MONEYTRANSFER               909
#define IDS_ERRADDCOWSTORRINV           910
#define IDD_BASESIMPLEINVOICE           910
#define IDD_SMALLINVOICE                910
#define IDS_ERRDELETINGCORRECTINVOICE   911
#define IDS_CANTADDDELCOWSBECOUSEINVOICE 912
#define IDD_AGENT                       912
#define IDS_CANTADDDELDOCSWHENEDITINGCORRECT 913
#define IDR_INVOICEDLGCHOICEMENU        913
#define IDS_CANTADDDELCOWSWHENEDITINGCORRECT 914
#define IDD_REPOACCOUNTSSYNCCTRLDLG     914
#define IDD_REPO_ACCOUNTSCTRL           914
#define IDS_ERRBADREGON                 915
#define IDD_ABBYCFG                     915
#define IDD_RECOGNITIONENGINECFG        915
#define IDS_ERRBADIDNO                  916
#define IDD_RECOGNITIONSCANNEROPTS      916
#define IDS_IMPORTINGDOCS               917
#define IDD_RECOGNITIONIMAGEOPTS        917
#define IDS_OCRERRNOPASSPROFILESELECTED 918
#define IDD_DIALOG3                     918
#define IDS_OCRERRFAILDTOINITENGINE     919
#define IDD_INVOICEDETAILSOPTS          919
#define IDS_FAILDTOSTOREPASSIMGASK      920
#define IDD_REPO_COMPANY                920
#define IDD_REPO_COMPANY_VIEW           920
#define IDS_FAILDTOASSIGNPASSIMGTOOWASK 921
#define IDD_REPO_PURACHES               921
#define IDD_REPO_PURCHASES              921
#define IDD_REPO_PURCHASES_VIEW         921
#define IDS_PLEASEWAIT                  922
#define IDD_REPO_ITEMS                  922
#define IDD_REPO_ITEMS_VIEW             922
#define IDS_GOTERRORUPDATINGCOWSCANTCONTINUE 923
#define IDD_PROGRESS_DLG                923
#define IDS_GOTERRORINSERTINGLONLYCOWSCANTCONTINUE 924
#define IDB_PNG1                        924
#define IDS_GOTERRORUPDATINGINDOCSCANTCONTINUE 925
#define IDB_PNG2                        925
#define IDS_ERRUPDATINGSYNCCOW          926
#define IDD_REPO_ACCOUNTDLG             926
#define IDS_ERROTUPDATINGSYNCINDOC      927
#define IDD_PSSPORT_SEGREGATION         927
#define IDD_PASSPORT_SEGREGATION        927
#define IDS_ERRINSERTINGSYNCCOW         928
#define IDD_REPO_PURACHE                928
#define IDD_REPO_PURCHASE               928
#define IDS_ERRINSERTINGSYNCINDOC       929
#define IDD_DIALOG2                     929
#define IDD_REPO_ACCOUNTPAGE            929
#define IDD_REPO_ACCOUNT_VIEW           929
#define IDS_ERRASSIGNINGSYNCCOWTOSYNCOUTDOC 930
#define IDD_DIFFERENCEDLG               930
#define IDS_ERRINSERTINGSYNCOUTDOC      931
#define IDD_REPO_PURCHASE_SUMMARY       931
#define IDS_ERRINVALIDSTOCKCODE         932
#define IDD_IDPZDOCOPT                  932
#define IDS_ERRUPDATEINGSTOCK           933
#define IDD_TRANSPORTDOCOPTDLG          933
#define IDS_EDITINGRACE                 934
#define IDS_NEWRACE                     935
#define IDS_DOCNAME_FAKRR_PIECE         936
#define IDS_DOCNAME_FAKRR3_PIECE        937
#define IDS_MISSINGNOSEXVALUE           938
#define IDS_ERRREADINGHKEY              939
#define IDS_ERRHKEYERR                  940
#define IDS_DOCNAME_EXPENSESSUM         942
#define IDS_USEDPREDEFSEX               943
#define IDS_ERRBADISSUEDATE             944
#define IDS_ASKFILLTAB                  945
#define IDS_DOCNAME_IDPZBARCODES        946
#define IDS_INVALIDMOTHEREAN            947
#define IDS_PRINTPREVIEW                948
#define IDS_DOCNAME_DYMOHENTLABEL       949
#define IDS_DOCNAME_FAKRRTERM3_WEIGHT   950
#define IDS_DYMO                        951
#define IDS_SEIKO                       952
#define IDS_WINPRINT                    953
#define IDS_PRINTERNOTSELECTED          954
#define IDS_DOCNAME_FAKRRTERM3_PIECE    955
#define IDS_HEADEREXPENSECATEGORYVATRATE 956
#define IDS_SEARCHININDOCS              957
#define IDS_SEARCHINOUTDOCS             958
#define IDS_HENTDATA_MEMBER_WETLICENCE  959
#define IDS_HENTDATA_MEMBER_CELLPHONENO 960
#define IDS_HENTDATA_MEMBER_EMAILADDRESS 961
#define IDS_HENTDATA_MEMBER_LATITUDE    962
#define IDS_HENTDATA_MEMBER_LONGITUDE   963
#define IDS_OTHERCOUNTRYMENUITEMTEXT    964
#define IDS_COUNTRYCODEMENUITEMTEXT     965
#define IDS_ASKDBUPDATE                 966
#define IDS_FAILEDTOUPDATEDB            967
#define IDS_FAILEDTOLOADDB              968
#define IDS_FASTFINDHENTCAPTION         969
#define IDS_FASTFINDHENTLBL             970
#define IDS_CANTCHNGPAIDDTDUETOCORRECT  971
#define IDS_ENTERCORRECTDATE            972
#define IDS_ASKFORPAIDDATELBL           973
#define IDS_ASKFORPAIDDATECAPTION       974
#define IDS_INVALIDPAIDDATE             975
#define IDS_DOCNAME_INTRANSPORTDOC      976
#define IDS_DOCNAME_OUTTRANSPORTDOC     977
#define IDS_HEADEROFFICIALSTOCKCODE     978
#define IDS_DOCNAME_KSIEGASTADA         979
#define IDS_EXPORTWITHVATINVSERROR      980
#define IDS_EXPORTOPTIONS               981
#define IDS_IMPORTOPTIONS               982
#define IDS_OPTDESCEXPORTINVOICES       983
#define IDS_OPTDESCEXPORTSELLBUYPRICE   984
#define IDS_OPTDESCEXPORTBUYSELLVALUES  986
#define IDS_OPTDESCEXPORTMYPRICEASMYPRICE 987
#define IDS_OPTDESCEXPORTPASSIMGS       988
#define IDS_DOCNAME_SPECFAKZEW          989
#define IDS_HEADERERROR                 990
#define IDS_MONEYTRANS_ALRADYPAID       991
#define IDS_MONEYTRANS_HENTHASNOACCNO   992
#define IDS_MONEYTRANS_PAIDBYCASH       993
#define IDS_HEADERINVVALUE              994
#define IDS_HEADERTRANSVALUE            995
#define IDS_OPTDESCIMPORTPASSIMGS       996
#define IDS_OPTDESCINSERTMISSINGSTOCKS  997
#define IDS_OPTDESCINSERTMISSINGHENTS   998
#define IDS_OPTDESCIMPORTSAVEDOCDATES   999
#define IDC_ACCOUNTNO                   1000
#define IDC_PRINTERLIST                 1000
#define IDS_OPTDESCIMPORTSAVEORIGINALHENT 1000
#define IDC_ACTIVEGRPCHECK              1001
#define IDS_IMPORTINPERUPTEDBYUSER      1001
#define IDC_ADDCOW                      1002
#define IDS_SELECTMONEYTRANSFERFORMAT   1002
#define IDC_ADDCOWS                     1003
#define IDC_COPIESEDIT                  1003
#define IDS_CREATINGMONEYTRANSFERFILE   1003
#define IDC_ADDDOC                      1004
#define IDC_BTNPLUS                     1004
#define IDS_EDITEXPENSECATEGORIES       1004
#define IDC_ADDHENT                     1005
#define IDC_BTNMINUS                    1005
#define IDS_EDITRULES                   1005
#define IDC_ADDITEM                     1006
#define IDC_NUMBEROFCOPIESLABEL         1006
#define IDS_EDITSTOCKS                  1006
#define IDC_ADDMODOWN                   1007
#define IDS_HEADERPLATE                 1007
#define IDC_ADDNEWCOW                   1008
#define IDS_EDITAGENTS                  1008
#define IDC_ADDRULE                     1009
#define IDS_EMPTYAGENTNAME              1009
#define IDC_ADDSTOCK                    1010
#define IDS_EMPTYAGENTCODE              1010
#define IDC_ADDTOFOUND                  1011
#define IDS_NEWAGENT                    1011
#define IDC_ADDUSER                     1012
#define IDS_ERRINSERTINGAGENT           1012
#define IDC_ADMIN                       1013
#define IDS_AGENTRECORDISUSED           1013
#define IDC_AGEMINUS                    1014
#define IDS_ERRDELETINGAGENT            1014
#define IDC_AGENTNAME                   1015
#define IDS_ERRUPDATEINGAGENT           1015
#define IDC_AGEPLUS                     1016
#define IDS_EDITAGENTCAPTION            1016
#define IDC_AGEWARNCOLOR                1017
#define IDS_HEADERAGENT                 1017
#define IDC_AGEWARNDATE                 1018
#define IDS_MONEYTRANS_HASCORRECT       1018
#define IDC_AIMRNO                      1019
#define IDS_CANTADDCOWSWHENCREATINGCORRECTINVOICE 1019
#define IDC_ALIAS                       1020
#define IDS_CANTDELCOWSWHENCREATINGCORRECTINVOICE 1020
#define IDC_AMOUNT                      1021
#define IDS_CANTADDDOCSWHENCREATINGCORRECTINVOICE 1021
#define IDC_AMOUNTSPAN                  1022
#define IDS_CANTDELDOCSWHENCREATINGCORRECTINVOICE 1022
#define IDC_ARCHIVEDIR                  1023
#define IDS_INVOICEDATEISBEFOREDOCDATE  1023
#define IDC_ARCHIVELIST                 1024
#define IDS_ERRSETTOTALWEIGHT           1024
#define IDC_EDITBOX                     1025
#define IDS_ASKFORWEIGHTCAPTION         1025
#define IDC_ASKATEXIT                   1026
#define IDS_ASKFORWEIGHTLABEL           1026
#define IDC_ASKBEFOREMOVE               1027
#define IDS_OCRERRFAILTOLOADIMGFROMFILE 1027
#define IDC_ASKFORDBLOC                 1028
#define IDS_OCRERRFAILETOLOADFROMDIB    1028
#define IDC_ASKLABEL                    1029
#define IDS_SCANPASSMENUCONFIGURE       1029
#define IDC_AUTOFEED                    1030
#define IDS_MUSTACHEERRNOTCLOSEDBRACKET 1030
#define IDC_AUTOLOGIN                   1031
#define IDS_MUSTACHEERRINVALIDESCAPE    1031
#define IDC_AUTOPASS                    1032
#define IDS_DECIMALPOINTLBL             1032
#define IDC_AUTOUSER                    1033
#define IDC_PRECISIONLBL                1033
#define IDC_BACKUPDIR                   1034
#define IDS_DOCNAME_VATINVCOMPACTWEIGHT 1034
#define IDC_BACKUPLIST                  1035
#define IDS_ERRHKEYEXPIREDFMT           1035
#define IDC_BANK                        1036
#define IDC_COMPANYBANK                 1036
#define IDS_ERRHKEYAPPREQUIREDUPDATEFMT 1036
#define IDC_BANKNAME                    1037
#define IDS_ERRHKETABSENTTOOLONGFMT     1037
#define IDC_BIRTHDATE                   1038
#define IDS_ERRHKEYINVALIDCLOCK         1038
#define IDC_BIRTHDATESPAN               1039
#define IDS_HENTTYPE_COMPANY            1039
#define IDC_BIRTHENABLE                 1040
#define IDS_HENTTYPE_INDIVIDUAL         1040
#define IDC_BIRTHPLACE                  1041
#define IDS_HEADER_DISCREPANCY          1041
#define IDC_BLACKLEVEL                  1042
#define IDS_NO_PLATE_NUMBERS            1042
#define IDC_BLACKLEVEL_VAL              1043
#define IDS_ERRNOVATRATE                1043
#define IDC_BRIGHTNESS                  1044
#define IDS_PURCHASE_INVOICES_TABTEXT   1044
#define IDC_BRIGHTNESS2                 1045
#define IDS_PURCHASE_HENTS_TABTEXT      1045
#define IDC_BRIGHTNESS3                 1046
#define IDS_HEADERSTARTDATETIME         1046
#define IDC_BRIGHTNESS_VAL              1047
#define IDS_DOCNAME_VATINVGRPPRICEPIECE 1047
#define IDC_BRIGHTNESS_VAL2             1048
#define IDS_DOCNAME_WEIGHTINGDOC        1048
#define IDC_BTNFIND                     1049
#define IDS_NEWREPOACCOUNT_DLG_CAPTION  1049
#define IDC_BURNPASSIMGDBFILE           1050
#define IDS_DOCNAME_VATINVGRPPRICEWEIGHT 1050
#define IDC_BUSY_TEXT                   1051
#define IDS_CONFIRMDELETEREPOACCOUNT    1051
#define IDC_BUTTON4                     1052
#define IDS_COWLABEL                    1052
#define IDS_PRINTCOWLABEL               1052
#define IDC_BUTTON5                     1053
#define IDS_REPO_UPDATINGCOMPANY        1053
#define IDC_BUYINVRADIO                 1054
#define IDS_REPO_CONNECTING             1054
#define IDC_BUYSELLLOSSCOLOR            1055
#define IDS_ERREMPTYPOBOX               1055
#define IDC_BUY_GT_LT_COMBO             1056
#define IDS_EDITREPOACCOUNT_DLG_CAPTION 1056
#define IDC_BYACCOUNTNO                 1057
#define IDS_HEADERDOWNLOADED            1057
#define IDC_BYAIMRNO                    1058
#define IDS_HEADERINVOICETYPE           1058
#define IDC_BYALIAS                     1059
#define IDS_INVOICETYPELUMP             1059
#define IDC_BYAMOUNT                    1060
#define IDS_INVOICETYPEREGULAR          1060
#define IDC_BYARIMRNO                   1061
#define IDS_PURCHASE_SUMMARY_TABTEXT    1061
#define IDC_BYBANKNAME                  1062
#define IDS_DOCNAME_NORMALIZEFOODCHAIN  1062
#define IDC_BYBIRTHPLACE                1063
#define IDS_DOCNAME_REGISTRACTION       1063
#define IDC_BYBUYER                     1064
#define IDC_BYBUYPRICE                  1065
#define IDC_BYBUYSTOCK                  1066
#define IDC_BYBUYWEIGHT                 1067
#define IDC_BYCITY                      1068
#define IDC_BYCOUNTRY                   1069
#define IDC_BYCREATION                  1070
#define IDC_BYCREATIONCHECK             1071
#define IDC_BYDELIVER                   1072
#define IDC_BYDOCDATE                   1073
#define IDC_BYEAN                       1074
#define IDC_BYFSTOWNR                   1075
#define IDC_BYHENT                      1076
#define IDC_BYHTYPE                     1077
#define IDC_BYIDNO                      1078
#define IDC_BYINVDATE                   1079
#define IDC_BYINVNOFROM                 1080
#define IDC_BYINVNOTO                   1081
#define IDC_BYINVTYPE                   1082
#define IDC_BYISSUEDATE                 1083
#define IDC_BYISSUEPOST                 1084
#define IDC_BYLOADDATE                  1085
#define IDC_BYMODIFICATION              1086
#define IDC_BYMODIFICATIONCHECK         1087
#define IDC_BYMOTHEREAN                 1088
#define IDC_BYNAME                      1089
#define IDC_BYNIP                       1090
#define IDC_BYPAID                      1091
#define IDC_BYPASSNO                    1092
#define IDC_BYPAYWAY                    1093
#define IDC_BYPESEL                     1094
#define IDC_BYPHONE                     1095
#define IDC_BYPLATE                     1096
#define IDC_BYPOBOX                     1097
#define IDC_BYREASON                    1098
#define IDC_BYREGON                     1099
#define IDC_BYSELLPRICE                 1100
#define IDC_BYSELLSTOCK                 1101
#define IDC_BYSELLWEIGHT                1102
#define IDC_BYSEX                       1103
#define IDC_BYSTOCK                     1104
#define IDC_BYSTREET                    1105
#define IDC_BYTOTAL                     1106
#define IDC_BYTRANSDATE                 1107
#define IDC_BYVATRATE                   1108
#define IDC_BYWEIGHT                    1109
#define IDC_BYWETNO                     1110
#define IDC_BYZIP                       1111
#define IDC_CALLDOCOPT                  1112
#define IDC_CENTER                      1113
#define IDC_CHANGE                      1114
#define IDC_CHART                       1115
#define IDC_CHECK2                      1116
#define IDC_EVENT_CHECK_SELL            1116
#define IDC_CHECKEANS                   1117
#define IDC_CHECKFARMNO                 1118
#define IDC_CHECKNOFSTOWNRUPDATEIFPRESENT 1119
#define IDC_NOUPDATEIFPRESENT           1119
#define IDC_CHECKPRICEPERKG             1120
#define IDC_CHECKSELHTYPE               1121
#define IDC_CHECKSELINREASON            1122
#define IDC_CHECKSELOURESON             1123
#define IDC_CHECKSELOUTREASON           1124
#define IDC_CHECKSELPAYWAY              1125
#define IDC_CHECKSELPAYWAYRR            1126
#define IDC_CHECKSELPAYWAYVAT           1127
#define IDC_CHECKSELSEX                 1128
#define IDC_CHECKSELSTOCK               1129
#define IDC_CHNGTAB                     1130
#define IDC_CITY                        1131
#define IDC_COLECTOR                    1132
#define IDC_COMBOHENTTYPES              1133
#define IDC_COMBOSEX                    1134
#define IDC_COMBOSTOCK                  1135
#define IDC_COMPORT                     1136
#define IDC_CONTRAST                    1137
#define IDC_CONTRAST2                   1138
#define IDC_CONTRAST3                   1139
#define IDC_CONTRAST_VAL                1140
#define IDC_CONTRAST_VAL2               1141
#define IDC_CORRECT                     1142
#define IDC_COUNT                       1143
#define IDC_COUNTRIES                   1144
#define IDC_COWCOUNT                    1145
#define IDC_COWDELETE                   1146
#define IDC_COWLIST                     1147
#define IDC_COWNOEDIT                   1148
#define IDC_COWPRICELIST                1149
#define IDC_COWSLEFT                    1150
#define IDC_CREATOR                     1151
#define IDC_CREATTIME                   1152
#define IDC_CREATUSER                   1153
#define IDC_CURRENTGROUP                1154
#define IDC_CUSTOMEVENTTYPE             1155
#define IDC_CUSTOMNUMBER                1156
#define IDC_CUSTOMPRICEPERKG            1157
#define IDC_DATA                        1158
#define IDC_DATABITS                    1159
#define IDC_DAYS                        1160
#define IDC_DEFAULTSTOCKCOMBO           1161
#define IDC_DELARCHIVEBTN               1162
#define IDC_DELCOPY                     1163
#define IDC_DELDOC                      1164
#define IDC_DELFORG                     1165
#define IDC_DELITEM                     1166
#define IDC_DELOWN                      1167
#define IDC_DELSTOCK                    1168
#define IDC_DELBTN                      1168
#define IDC_DELUSER                     1169
#define IDC_DIFFLIST                    1170
#define IDC_DISCOUNTFEE                 1171
#define IDC_DISCOUNTVAT                 1172
#define IDC_DOARCHIVE                   1173
#define IDC_DOCDATE                     1174
#define IDC_DOCHENT                     1175
#define IDC_DOCLIST                     1176
#define IDC_DOCNO                       1177
#define IDC_DOCNOEDIT                   1178
#define IDC_DOCNOFROM                   1179
#define IDC_DOCNOTO                     1180
#define IDC_DOCOPTIONS                  1181
#define IDC_DOCPLATENO                  1182
#define IDC_DONTFILLPLATENO             1183
#define IDC_DOPALETENHANCE              1184
#define IDC_DOPASSDBARCHIVE             1185
#define IDC_DOPASSIMGBACKUP             1186
#define IDC_DOSCAN                      1187
#define IDC_DOSYNC                      1188
#define IDC_DOUBLECHECK                 1189
#define IDC_EAN                         1190
#define IDC_EANEDIT                     1191
#define IDC_EXPORTMYPRICEASMYPRICE      1192
#define IDC_EXPORTMYPRICEPERKG          1193
#define IDC_EXPORTPASSIMGS              1194
#define IDC_EXPORTPRICEASMYPRICE        1195
#define IDC_EXPPORTBUYSELLVALUES        1196
#define IDC_EXTRAS                      1197
#define IDC_FARMNO                      1198
#define IDC_FIN                         1199
#define IDC_FINDEXTRAS                  1200
#define IDC_FINDPASSPORT                1201
#define IDC_FINDPASSPORTS               1202
#define IDC_FINDTAB                     1203
#define IDC_COMPANYFARMNO               1204
#define IDC_COMPANYCITY                 1205
#define IDC_COMPANYNAME                 1206
#define IDC_COMPANYPOBOX                1207
#define IDC_COMPANYREGON                1208
#define IDC_COMPANYSTREET               1209
#define IDC_COMPANYWETIDNO              1210
#define IDC_COMPANYZIP                  1211
#define IDC_FLOW                        1212
#define IDC_FONTHEIGHT                  1213
#define IDC_FONTHEIGHTEDIT              1214
#define IDC_FORMCOUNT                   1215
#define IDC_FOUNDLABEL                  1216
#define IDC_GETCOW                      1217
#define IDC_GETCOWS                     1218
#define IDC_GETDATA                     1219
#define IDC_GETSELECT                   1220
#define IDC_PREVIEW                     1220
#define IDC_PRINTPREVIEW                1220
#define IDC_GOPRINT                     1221
#define IDC_GOSEARCH                    1222
#define IDC_GROUPBOX_DOCOPT             1223
#define IDC_GROUPBYSTOCK                1224
#define IDC_GRPCLRCOMBO                 1225
#define IDC_GRPCOMBO                    1226
#define IDC_HEIGHTSPIN                  1227
#define IDC_HENTADD                     1228
#define IDC_HENTCANCEL                  1229
#define IDC_HENTCITY                    1230
#define IDC_HENTCOMBO                   1231
#define IDC_HENTNAME                    1232
#define IDC_HENTOWNER                   1233
#define IDC_HENTPOBOX                   1234
#define IDC_HENTSTREET                  1235
#define IDC_HENTZIP                     1236
#define IDC_HTYPE                       1237
#define IDC_IDNUMBER                    1238
#define IDC_IMPORTPASSIMGS              1239
#define IDC_INFOTEXT                    1240
#define IDC_ININCOWS                    1241
#define IDC_INRESULT                    1242
#define IDC_INSERTMISSINGHENTS          1243
#define IDC_INSERTMISSINGSTOCKS         1244
#define IDC_INSERTOPT                   1245
#define IDC_INVDATESPAN                 1246
#define IDC_INVOICEDATE                 1247
#define IDC_INVTYPE                     1248
#define IDC_ISSUEDATE                   1249
#define IDC_ISSUEPOST                   1250
#define IDC_ISSUETEXT                   1251
#define IDC_ISSUEVALUEEDIT              1252
#define IDC_ISSUEVALUENAME              1253
#define IDC_LABELWARN                   1254
#define IDC_LASTCOPY                    1255
#define IDC_LASTSEARCHRESULT            1256
#define IDC_LASTSEARCHSTATUS            1256
#define IDC_LICENCEDTO                  1257
#define IDC_LIMAGE                      1258
#define IDC_LIMWEIGHT                   1259
#define IDC_LIST                        1260
#define IDC_LMODIFIER                   1261
#define IDC_LMODIFYTIME                 1262
#define IDC_LOADDATE                    1263
#define IDC_LOGCANCEL                   1264
#define IDC_LOGIN                       1265
#define IDC_LPEDIT                      1266
#define IDC_MAKECOPY                    1267
#define IDC_MAKEDBCOPY                  1268
#define IDC_MAKEINVOICE                 1269
#define IDC_MARGINSCTRL                 1270
#define IDC_MARKAGECOLOR                1271
#define IDC_MARKBUYSELLLOSS             1272
#define IDC_MARKCOWAGE                  1273
#define IDC_MARKDAYAGE                  1274
#define IDC_MARKMYPRICELOSSBUY          1275
#define IDC_MARKMYPRICELOSSSELL         1276
#define IDC_MARK_FOUND_COW              1277
#define IDC_MASKMYPRICE                 1278
#define IDC_MAXPROFITEDIT               1279
#define IDC_MERGETEXT                   1280
#define IDC_MODFORG                     1281
#define IDC_MODIFTIME                   1282
#define IDC_MODIFYUSER                  1283
#define IDC_MOTHEREAN                   1284
#define IDC_MOTHERNO                    1285
#define IDC_MOUNTEDLIST                 1286
#define IDC_MOVENOW                     1287
#define IDC_MYPRICE                     1288
#define IDC_NAME                        1289
#define IDC_NAMECOMBO                   1290
#define IDC_NAMEVERSION                 1291
#define IDC_NAVTAB                      1292
#define IDC_NAZWALICZEB1                1293
#define IDC_NAZWALICZEB2_4              1294
#define IDC_NAZWALICZEBRESZTA           1295
#define IDC_NEINDOCEXTRAS               1296
#define IDC_NEWCOWADDHENT               1297
#define IDC_NEWCOWCANCEL                1298
#define IDC_NEWCOWEXTRAS                1299
#define IDC_NEWINDOCCANCEL              1300
#define IDC_NEWSEARCH                   1301
#define IDC_NEWSTOCKCODE                1302
#define IDC_NEWSTOCKEDIT                1303
#define IDC_NEWSTOCKNAME                1304
#define IDC_NEWSTOCKOK                  1305
#define IDC_NEXT                        1306
#define IDC_NEXTNEXT                    1307
#define IDC_NIP                         1308
#define IDC_NOEVENTTYPE                 1309
#define IDC_OKBUTTON                    1310
#define IDC_ONEBYONE                    1311
#define IDC_OPTFIELDS                   1312
#define IDC_OPTIONS                     1313
#define IDC_OUTGRPSUMMARYLIST           1314
#define IDC_PAGENUM                     1315
#define IDC_PAIDDATE                    1316
#define IDC_PARITY                      1317
#define IDC_PASS                        1318
#define IDC_PASSDATE                    1319
#define IDC_PASSDATESPAN                1320
#define IDC_PASSDBMAXSIZE               1321
#define IDC_PASSDBMOVEDIR               1322
#define IDC_PASSENABLE                  1323
#define IDC_PASSIMGBDSIZE               1324
#define IDC_PASSIMGVIEW                 1325
#define IDC_PASSLABEL                   1326
#define IDC_PASSNO                      1327
#define IDC_PASSWORD                    1328
#define IDC_PAYDUEDAYSRRAPIN            1329
#define IDC_PAYDUEDAYSRRVALUE           1330
#define IDC_PAYDUEDAYSSPIN              1331
#define IDC_PAYDUEDAYSVATSPIN           1332
#define IDC_PAYDUEDAYSVATVALUE          1333
#define IDC_PAYWAY                      1334
#define IDC_PESEL                       1335
#define IDC_PHONE                       1336
#define IDC_PKWIU                       1337
#define IDC_PLATE                       1338
#define IDC_PLATENO                     1339
#define IDC_POBOX                       1340
#define IDC_PRESELPAYWAY                1341
#define IDC_PRESELPAYWAYRR              1342
#define IDC_PRESELPAYWAYVAT             1343
#define IDC_PRESELVATRATE               1344
#define IDC_PRESELVATRATERR             1345
#define IDC_PRESELVATRATEVAT            1346
#define IDC_PREV                        1347
#define IDC_PREVPREV                    1348
#define IDC_PRINTALL                    1349
#define IDC_PRINTCOWLIST                1350
#define IDC_PRINTLIST                   1350
#define IDC_PRINTDOC                    1351
#define IDC_PRINTDOCOPT                 1352
#define IDC_PRINTDOCTYPE                1353
#define IDC_PRINTEXTRAS                 1354
#define IDC_PRINTFONTCOMBO              1355
#define IDC_PRINTINFORM                 1356
#define IDC_PRINTOPT                    1357
#define IDC_PROCESSBIRTHPLACE           1358
#define IDC_PROGDLG_PERCENT             1359
#define IDC_PROGDLG_PROGRESS            1360
#define IDC_PUTHENTNAME                 1361
#define IDC_RADIOADDTOFOUND             1362
#define IDC_RADIOINDOC                  1363
#define IDC_RADIOINRESULT               1364
#define IDC_RADIONEWSEARCH              1365
#define IDC_RADIOOUTDOC                 1366
#define IDC_REASON                      1367
#define IDC_REGON                       1368
#define IDC_REJECTEDLIST                1369
#define IDC_REJECTREASONGRPBOX          1370
#define IDC_REJECTREASONTEXT            1371
#define IDC_REJREFRESH                  1372
#define IDC_REPLACEITEMSCOMBO           1373
#define IDC_REPLACEOPT                  1374
#define IDC_REQUIREWEIGHT               1375
#define IDC_RESOLUTIONCOMBO             1376
#define IDC_RESOLUTION_VAL              1377
#define IDC_RESTORECOPY                 1378
#define IDC_RETYPE                      1379
#define IDC_RRINVRADIO                  1380
#define IDC_RULE4ALL                    1381
#define IDC_RULECOMBO                   1382
#define IDC_RULEDETAILS                 1384
#define IDC_RULEEDIT                    1385
#define IDC_RULELIST                    1386
#define IDC_RULENAME                    1387
#define IDC_SAMEASXY                    1388
#define IDC_SAVEORIGINALDOCDATES        1389
#define IDC_SAVEORIGINALHENT            1390
#define IDC_SAVEPASSIMG                 1391
#define IDC_SCANNINGFINISHED            1392
#define IDC_SCANPASS                    1393
#define IDC_SEARCHGROUP                 1394
#define IDC_SELECTSCANNER               1395
#define IDC_SELHTYPE                    1396
#define IDC_SELINANIMALS                1397
#define IDC_SELINHENTS                  1398
#define IDC_SELININCOWS                 1399
#define IDC_SELININDOCS                 1400
#define IDC_SELINOUTDOCS                1401
#define IDC_SELINREASON                 1402
#define IDC_SELLINVRADIO                1403
#define IDC_SELL_GT_LT_COMBO            1404
#define IDC_SELOUTREASON                1405
#define IDC_SELSEX                      1406
#define IDC_SELSTOCK                    1407
#define IDC_SEL_FOUND_COW               1408
#define IDC_SENDDATA                    1409
#define IDC_SERIALNUM                   1410
#define IDC_SETDEFAULT                  1411
#define IDC_SETTERMPRICEALL             1412
#define IDC_SETTERMPRICEBTN             1413
#define IDC_SETTERMSTOCKALL             1414
#define IDC_SETTERMSTOCKBTN             1415
#define IDC_SETTERMWEIGHTALL            1416
#define IDC_SETTERMWEIGHTBTN            1417
#define IDC_SETTOTAL                    1418
#define IDC_SETTOTALBRUTTO              1419
#define IDC_SETTOTALNETTO               1420
#define IDC_SEX                         1421
#define IDC_SHOWLIST                    1422
#define IDC_SHOWPREVIEW                 1423
#define IDC_SHOWTAB                     1424
#define IDC_SHOWWELCOME                 1425
#define IDC_SIGMA                       1426
#define IDC_SORTCOMBO                   1427
#define IDC_SORTFOUND                   1428
#define IDC_SORTORDER                   1429
#define IDC_SOURCE                      1430
#define IDC_SPEED                       1431
#define IDC_STATICDATEIN                1432
#define IDC_STATICDELIVER               1433
#define IDC_STATICHENT                  1434
#define IDC_STATUSMSG                   1435
#define IDC_STOCK                       1436
#define IDC_STOCKADD                    1437
#define IDC_STOCKLIST                   1438
#define IDC_STOCKSTATLIST               1439
#define IDC_STOPBITS                    1440
#define IDC_STREET                      1441
#define IDC_SYNCHSTATUS                 1442
#define IDC_SYNCLOG                     1443
#define IDC_SYNCPROGRESS                1444
#define IDC_TAB                         1445
#define IDC_TAB1                        1446
#define IDC_TASKNAME                    1447
#define IDC_TERMPRICE_LABEL             1448
#define IDC_TERMPRICE_VALUE             1449
#define IDC_TERMSTOCK_LABEL             1450
#define IDC_TERMSTOCK_VALUE             1451
#define IDC_TERMWEIGHT_LABEL            1452
#define IDC_TERMWEIGHT_VALUE            1453
#define IDC_TEST                        1454
#define IDC_TIMESPAN                    1455
#define IDC_TOTAL                       1456
#define IDC_TOTALBRUTTO                 1457
#define IDC_TOTALNETTO                  1458
#define IDC_TOTALVALUE                  1459
#define IDC_TOTALVAT                    1460
#define IDC_TRANSDATESPAN               1461
#define IDC_TRANSFEE                    1462
#define IDC_TRANSPDATE                  1463
#define IDC_UNLOCKHENT                  1464
#define IDC_UPPERCASEHENTDATA           1465
#define IDC_USEDEFAULTSTOCK             1466
#define IDC_USEFORNEXTALL               1467
#define IDC_USEINVVALUES                1468
#define IDC_USEMYPERKGPRICE             1469
#define IDC_USER                        1470
#define IDC_USERFNAME                   1471
#define IDC_USERFONTCHECK               1472
#define IDC_USERFONTGROUP               1473
#define IDC_USERLABEL                   1474
#define IDC_USERLIST                    1475
#define IDC_USERLNAME                   1476
#define IDC_USERNAME                    1477
#define IDC_VAT                         1478
#define IDC_VATVALUE                    1479
#define IDC_WARNBEFOREDATE              1480
#define IDC_WARNDATE                    1481
#define IDC_WARNDAYS                    1482
#define IDC_WARNEMPTYPLATENO            1483
#define IDC_WARNTOBIGPRICECLR           1484
#define IDC_WARNTOBIGPROFIT             1485
#define IDC_WARNTOSMALLPRICE            1486
#define IDC_WARNTOSMALLPRICECHECK       1487
#define IDC_WEIGHT                      1488
#define IDC_WEIGHTEDIT                  1489
#define IDC_WEIGHTRANGE                 1490
#define IDC_WETNO                       1491
#define IDC_XXPRICEBELOW                1492
#define IDC_XXPRICEOVER                 1493
#define IDC_XYPRICEBELOW                1494
#define IDC_XYPRICEOVER                 1495
#define IDC_ZIP                         1496
#define IDC_INDICATOR_STATISTICS        1497
#define IDC_INDICATOR_NOPASSIMGDB       1498
#define IDC_FASTSELECT_EDIT             1499
#define IDC_PAYDUEDAYS                  1500
#define IDC_LIST1                       1504
#define IDC_COWSTATLIST                 1504
#define IDC_COWSTOCKSTATLIST            1504
#define IDC_PASSPROFILESLIST            1504
#define IDC_HERDSLIST                   1504
#define IDC_OPTIONSLIST                 1504
#define IDC_MONEYTRANSERLIST            1504
#define IDC_CONNERCTEDCLIENTSLIST       1504
#define IDC_EXPENSECATEGORYNAME         1505
#define IDC_PURACHELIST                 1505
#define IDC_EXPENSECATEGORYDESC         1506
#define IDC_INVOICELIST                 1506
#define IDC_EXPENSEVAT                  1508
#define IDC_EXPENSEVALUE                1509
#define IDC_EXPENSETYPECOMBO            1510
#define IDC_INVOICENO                   1511
#define IDC_EXPENSEEXTRAS               1513
#define IDC_COMBO1                      1515
#define IDC_EXPENSECATEGORY             1515
#define IDC_PREDEFSEXCB                 1515
#define IDC_NOSEXVALUECB                1515
#define IDC_HERDCB                      1515
#define IDC_FORMATSELECTCOMBO           1515
#define IDC_AGENTCOMBO                  1515
#define IDC_EXPENSETITLEEDIT            1516
#define IDC_BYEXPENSEINVNOEDIT          1518
#define IDC_BYEXPENSECATEGORY           1519
#define IDC_BYEXPENSETITLEEDIT          1520
#define IDC_BYEXPENSETYPECOMBO          1521
#define IDC_EXPENSEDATE                 1522
#define IDC_BYGROSVALUE                 1523
#define IDC_BYEXPENSEDATE               1524
#define IDC_ABORTBTN                    1525
#define IDC_PROGRESS1                   1526
#define IDC_TASKPROGRESS                1526
#define IDC_INDICATOR_BARCODESCANNER    1527
#define IDC_ENTRYTEXT                   1529
#define IDC_BARCODE                     1530
#define IDC_OVERRIDE                    1531
#define IDC_STATUS                      1533
#define IDC_BUTTON1                     1534
#define IDC_SELECTALL                   1534
#define IDC_OCRAGAIN                    1534
#define IDC_EDITSTOCK                   1534
#define IDC_REFRESHPRINTERS             1534
#define IDC_SETCURRENTGEOCOORGS         1534
#define IDC_SETLOADTIMESTART            1534
#define IDC_NEXTPAGE                    1534
#define IDC_SAVEOPTIONS                 1534
#define IDC_DELETEENTRY                 1534
#define IDC_SAVEANDUSE                  1534
#define IDC_CHANGEINVENTRY              1534
#define IDC_EDITBTN                     1534
#define IDC_PRINTINVOICE                1534
#define IDC_STARTSERVICEBTN             1534
#define IDC_UPGRADEKEY                  1534
#define IDC_STOCKCODE                   1535
#define IDC_SETLOADTIMEEND              1535
#define IDC_STOCKNAME                   1536
#define IDC_SETLOADTIMESTART2           1536
#define IDC_SETPLATENOMENUBTN           1536
#define IDC_MYPRICEPERKG                1537
#define IDC_STOCKRULECB                 1538
#define IDC_CELLPHONENO                 1539
#define IDC_OFFICIALSTOCKCODE           1539
#define IDC_EMAILADDRESS                1540
#define IDS_HKEY_NOTPRESENT_PROGRESS    1542
#define IDC_PRINTDELETE                 1543
#define IDC_COPIES_2                    1544
#define IDC_PRINTDOCTYPESLIST           1544
#define IDC_COPIES_1                    1545
#define IDC_COPIES_4                    1545
#define IDC_WETLICENCENO                1545
#define IDC_COPIES_3                    1546
#define IDC_EDIT2                       1546
#define IDC_LATITUDE                    1546
#define IDC_INVOICEEXATRASTEMPLATE      1546
#define IDC_LICENSEFILEPATH             1546
#define IDC_REPO_ADDRESS                1546
#define IDC_EDIT3                       1547
#define IDC_LONGITUDE                   1547
#define IDC_AGENTPLATENO                1547
#define IDC_DEVELOPERSN                 1547
#define IDC_INVOICETITLE                1547
#define IDC_REPO_LOGIN                  1547
#define IDC_DEFAULTVATRATE              1548
#define IDC_LOADTIMESTART               1549
#define IDC_LOADTIMEEND                 1550
#define IDC_PREVPAGE                    1551
#define IDC_PRINTPREVIEWAREA            1553
#define IDC_EDITBOXDLGLBL               1555
#define IDC_ADDHERD                     1556
#define IDC_DELHERD                     1557
#define IDC_HERDNO                      1557
#define IDC_MODIFYHERD                  1558
#define IDC_HEDRCODE                    1558
#define IDC_HERDNAME                    1559
#define IDC_CURRENCYCOMBO               1560
#define IDC_EXCHANGERATE                1561
#define IDC_USEONLYONCE                 1562
#define IDC_ADDBTN                      1563
#define IDC_AGENTCODE                   1564
#define IDC_TRANSFERDATE                1565
#define IDC_SETTOTALWEIGHT              1569
#define IDC_TOTALWEIGHT                 1570
#define IDC_USECUSTOMPRICEPERKGCOLORLBL 1571
#define IDC_USEMYPRICEPERKGCOLORLBL     1572
#define IDC_STOPSERVICEBTN              1573
#define IDC_HOSTNAMELBL                 1574
#define IDC_EDIT1                       1575
#define IDC_ENGINEPATH                  1575
#define IDC_INVOICEENTRYTEXTFORMAT      1575
#define IDC_HEALTHCERTNO                1575
#define IDC_REPO_ACCOUNT_NAME           1575
#define IDC_EDIT4                       1576
#define IDC_PROJECTID                   1576
#define IDC_REPO_PASSWORD               1576
#define IDC_BUTTON2                     1577
#define IDC_SETTRANSACTIONPLACE         1577
#define IDC_CLEARAGENT                  1577
#define IDC_MONEYFORMAT                 1578
#define IDC_WEIGHTFORMAT                1579
#define IDC_PRICEPERKGFORMAT            1580
#define IDC_INVOICEENTRYFORMATHELP      1581
#define IDC_TRANSACTIONDATE             1582
#define IDC_TRANSACTIONPLACE            1583
#define IDC_COMAPNYPOBOX                1584
#define IDC_COMPANYNIP                  1585
#define IDC_COMPANYWETLICENCENO         1586
#define IDC_COMPANYACCOUNTNO            1587
#define IDC_KEYSTATELABEL               1588
#define IDC_TREE1                       1589
#define IDC_ACCOUNTSTREE                1589
#define IDC_BUTTON3                     1590
#define IDC_LOCAL_COMPANY_NAME          1594
#define IDC_REPO_COMPANY_NAME           1595
#define IDC_LOCAL_COMPANY_STREET        1596
#define IDC_LOCAL_COMPANY_POBOX         1597
#define IDC_LOCAL_COMPANY_CITY          1598
#define IDC_LOCAL_COMPANY_ZIPCODE       1599
#define IDC_LOCAL_COMPANY_FARMNO        1600
#define IDC_LOCAL_COMPANY_NIP           1601
#define IDC_LOCAL_COMPANY_REGON         1602
#define IDC_LOCAL_COMPANY_WETIDNO       1603
#define IDC_LOCAL_COMPANY_WETLICNO      1604
#define IDC_LOCAL_COMPANY_BANKACCOUNTNO 1605
#define IDC_LOCAL_COMPANY_BANKNAME      1606
#define IDC_REPO_COMPANY_STREET         1607
#define IDC_REPO_COMPANY_POBOX          1608
#define IDC_REPO_COMPANY_CITY           1609
#define IDC_REPO_COMPANY_ZIPCODE        1610
#define IDC_REPO_COMPANY_FARMNO         1611
#define IDC_REPO_COMPANY_NIP            1612
#define IDC_REPO_COMPANY_REGON          1613
#define IDC_REPO_COMPANY_WETIDNO        1614
#define IDC_REPO_COMPANY_WETLICNO       1615
#define IDC_REPO_COMPANY_BANKACCOUNTNO  1616
#define IDC_REPO_COMPANY_BANKNAME       1617
#define IDC_ITEMLIST                    1618
#define IDC_PROGRESS                    1619
#define IDC_ACCOUNTS_TOOLBAR            1620
#define IDC_MISSING_REMOTE_SIDE         1621
#define IDC_MISSING_LOCAL_SIDE          1622
#define IDC_BOTH_SIDES_NOT_EQUAL        1623
#define IDC_REPOCTRL_TOOLBAR            1625
#define IDC_SEGREGATION_STATUS          1625
#define IDC_PURACHE_INVOICE_COW_LIST    1626
#define IDC_PURACHE_INVOICE_LIST        1627
#define IDC_EVENT_CHECK_BUY             1628
#define IDC_EVENT_CHECK_BUY_AND_SELL    1629
#define IDC_EVENT_CHECK_EXPORT_TO_EU    1630
#define IDC_EVENT_CHECK_EXPORT_NOT_TO_EU 1631
#define IDC_EVENT_CHECK_OTHER           1632
#define IDC_CUSTOMEVENT_TYPE_GROUP      1633
#define IDC_PURCHASETAB                 1634
#define IDC_PURCHASETABS                1635
#define IDPNG_REPOACCOUNT_CONNECT       1636
#define IDPNG_REPOACCOUNT_DISCONNECT    1637
#define IDPNG_REPOACCOUNT_ADD           1638
#define IDPNG_REPOACCOUNT_DELETE        1639
#define IDPNG_REPOACCOUNT_REFRESH       1640
#define IDPNG_REPOACCOUNT_CHECKBOX      1641
#define IDPNG_REPOACCOUNT_BOX           1642
#define IDPNG_REPOACCOUNT_DOWNLOAD      1643
#define IDPNG_REPOACCOUNT_UPLOAD        1644
#define IDC_EXIT_TOOLBAR                1645
#define IDPNG_REPOACCOUNT_CLOSE         1646
#define IDC_VIEWHOLDER                  1647
#define IDPNG_REPOACCOUNT_EDIT          1648
#define IDC_DIFFLISTPLACEHOLDER         1649
#define IDC_PURCHASE_TOTAL_COWCOUNT     1650
#define IDC_PURCHASE_TOTAL_WEIGHT       1651
#define IDC_PURCHASE_TOTAL_NET          1652
#define IDC_PURCHASE_TOTAL_GROSS        1653
#define IDC_PURCHASE_TOTAL_TRANS_COWCOUNT 1654
#define IDC_PURCHASE_TOTAL_CASH_COWCOUNT 1655
#define IDC_PURCHASE_TOTAL_TRANS_WEIGHT 1656
#define IDC_PURCHASE_TOTAL_TRANS_NET    1657
#define IDC_PURCHASE_TOTAL_TRANS_GROSS  1658
#define IDC_PURCHASE_TOTAL_CASH_WEIGHT  1659
#define IDC_PURCHASE_TOTAL_CASH_NET     1660
#define IDC_PURCHASE_TOTAL_CASH_GROSS   1661
#define IDC_SPIECIES                    1662
#define IDC_DONFILLCARRIER              1663
#define IDC_DONTFILLCARRIER             1663
#define IDC_CHECK1                      1664
#define IDC_DONTFILLDESTFARMNO          1664
#define IDM_HENTCOMBO_POP_FINDHENT      32000
#define IDM_HENTCOMBO_POP_ADDHENT       32001
#define IDM_HENTCOMBO_POP_ALLHENTS      32002
#define IDM_HENTCOMBO_POP_ONLYCOMPANIES 32003
#define IDM_HENTCOMBO_POP_ONLYINDIVIDUALS 32004
#define IDM_EDITPOPUP_COPY              32045
#define IDM_EDITPOPUP_CUT               32046
#define IDM_EDITPOPUP_DELETE            32047
#define IDM_EDITPOPUP_PASTE             32048
#define IDM_EDITPOPUP_SELECTALL         32049
#define IDM_EDITPOPUP_UNDO              32050
#define IDMM_LOAD_ARCHIVE               32051
#define IDMM_LOAD_BACKUP                32052
#define IDMM_LOAD_CUSTOMPATH            32053
#define IDMM_LOAD_PRIMARYBASE           32054
#define IDMM_STOCKEDIT                  32055
#define IDMM_LOGOUT                     32056
#define IDMM_RULEEDIT                   32057
#define IDMM_DAYSTATS                   32058
#define IDM_TOOLBAR_EXIT                32059
#define IDM_TOOLBAR_FAST_SELECT         32060
#define IDM_TOOLBAR_FIND                32061
#define IDM_TOOLBAR_NEWHENT             32062
#define IDM_TOOLBAR_NEWINDOC            32063
#define IDM_TOOLBAR_NEWOUTDOC           32064
#define IDM_TOOLBAR_OPTIONS             32065
#define IDM_TOOLBAR_SHOWALL             32067
#define IDM_TOOLBAR_TERMSYNC            32068
#define IDM_TOOLBAR_NEWEXPENSE          32069
#define IDM_TOOLBAR_HENTSYNC            32070
#define IDM_COWLIST_EDITCOW             32077
#define IDM_COWLIST_SHOWPASSIMG         32078
#define IDM_MOUNT_CHNGPATH              32086
#define IDM_MOUNT_MOUNT                 32087
#define IDM_MOUNT_UNMOUNT               32088
#define IDM_MENUBARCHECK                32091
#define IDA_DELROW                      32092
#define IDA_DLGINSERTNEW                32093
#define IDA_DLGINSERTNEWSHIFT           32094
#define IDA_INSERTNEW                   32095
#define IDA_INSERTNEW2                  32096
#define IDA_INSERTNEWSHIFT              32097
#define IDA_MARKROW                     32098
#define IDA_UNMARKROW                   32099
#define IDM_PRICELIST_MIN               32100
#define IDM_PRICELIST_DELCUSTPRICE      32101
#define IDM_PRICELIST_DELCUSTPRICEALL   32102
#define IDM_PRICELIST_DELCUSTSTOCK      32103
#define IDM_PRICELIST_DELCUSTSTOCKALL   32104
#define IDM_PRICELIST_DELCUSTWEIGHT     32105
#define IDM_PRICELIST_DELCUSTWEIGHTALL  32106
#define IDM_PRICELIST_SHOWPASSIMG       32107
#define IDM_PRICELIST_DELALLCUSTVALUES  32108
#define IDM_PRICELIST_DELALLCUSTVALUESALL 32109
#define IDM_PRICELIST_MAX               32200
#define IDM_GRID_COMMANDS_MIN           32201
#define IDM_GRID_COWS_SHOWSTOCKSTAT     32202
#define IDM_GRID_DELETEROW              32203
#define IDM_GRID_DOC_MAKEINVOICE        32204
#define IDM_GRID_EDITROW                32205
#define IDM_GRID_FASTCOWSEARCH          32206
#define IDM_GRID_INDOC_MAKEOUTDOC       32207
#define IDM_GRID_INVERTSELECTION        32208
#define IDM_GRID_INV_EDITCORRECT        32209
#define IDM_GRID_INV_ADDPAYADVANCE      32210
#define IDM_GRID_INV_MONEYTRANSFER      32211
#define IDM_GRID_ROWPROPERTIES          32213
#define IDM_GRID_SELECTALL              32214
#define IDM_GRID_SELECTMARKED           32215
#define IDM_GRID_SORTMARKED             32216
#define IDM_GRID_UNMARK                 32217
#define IDM_GRID_PRINT                  32218
#define IDM_GRID_DOC_EXCELEXPORT        32219
#define IDM_GRID_INDOC_IMPORTFROMFILE   32220
#define IDM_GDIR_DOC_EXPORTTOFILE       32221
#define IDM_GRID_COWS_MAKERRINVOICE     32222
#define IDM_GRID_COWS_SHOWHIDEMYPRICE   32223
#define IDM_GRID_COWS_PRINTCOWLABEL     32224
#define IDM_GRID_HENTS_HENTSYNCIT_N     32225
#define IDM_GRID_HENTS_HENTSYNCIT_Y     32226
#define IDM_GRID_SHOWMENU_MIN           32227
#define IDM_GRID_SHOWMENU_SHOWBUYER     32228
#define IDM_GRID_SHOWMENU_SHOWBUYINV    32229
#define IDM_GRID_SHOWMENU_SHOWDELIVER   32230
#define IDM_GRID_SHOWMENU_SHOWFSTOWNR   32231
#define IDM_GRID_SHOWMENU_SHOWINDOC     32232
#define IDM_GRID_SHOWMENU_SHOWOUTDOC    32233
#define IDM_GRID_SHOWMENU_SHOWRRINV     32234
#define IDM_GRID_SHOWMENU_SHOWSELLINV   32235
#define IDM_GRID_SHOWMENU_PASSIMG       32236
#define IDM_GRID_SHOWMENU_MAX           32240
#define IDM_GRID_SUMMENU_MIN            32241
#define IDM_GRID_SUMMENU_SUMBUYPRICE    32242
#define IDM_GRID_SUMMENU_SUMMYPRICE     32243
#define IDM_GRID_SUMMENU_SUMSELLPRICE   32244
#define IDM_GRID_SUMMENU_MAX            32250
#define IDM_GRID_SUMMENU_SUB_MIN        32251
#define IDM_GRID_SUMMENU_SUB_SELLBUYPRICE 32252
#define IDM_GRID_SUMMENU_SUB_SELLMYPRICE 32253
#define IDM_GRID_SUMMENU_SUB_BUYMYPRICE 32254
#define IDM_GRID_SUMMENU_SUB_MAX        32260
#define IDM_GRID_MARKPAID_YES_NOW       32261
#define IDM_GRID_MARKPAID_YES_DATE      32262
#define IDM_GRID_MARKPAID_NO            32263
#define IDM_GRID_COMMANDS_MAX           32400
#define IDM_OUTGRPMENU_BASE             32401
#define IDM_OUTGRPMENU_MAX              32499
#define IDM_OUTGRPMENU_NOGRP            32500
#define IDM_TOOLBAR_FASTSELECT_MIN      32501
#define IDM_TOOLBAR_FASTSELECT_BTN_GO   32502
#define IDM_TOOLBAR_FASTSELECT_BTN_OPT  32503
#define IDM_FASTSELECT_MENU_MIN         32510
#define IDM_FASTSELECT_MENU_FINDFIRSTROW 32511
#define IDM_FASTSELECT_MENU_MARKFOUND   32512
#define IDM_FASTSELECT_MENU_SELECTFOUND 32513
#define IDM_FASTSELECT_MENU_SETPOSONROW 32514
#define IDM_FASTSELECT_MENU_MAX         32550
#define IDM_TOOLBAR_FASTSELECT_MAX      32551
#define IDMM_EDITEXPENSECATEGORIES      32554
#define IDM_TOOLBAR_GRIDFONTZOOMOUT     32555
#define IDM_TOOLBAR_GRIDFONTZOOMIN      32556
#define IDM_TOOLBAR_GRIDGOTOBOTTOM      32557
#define IDM_TOOLBAR_GRIDGOTOTOP         32558
#define IDMM_EDITAGENTS                 32560
#define IDMM_SMALLINVOICEDLG            32562
#define IDMM_BIGINVOICEDLG              32564
#define IDM_BIGINVOICEDLG               32565
#define IDM_SMALLINVOICEDLG             32566
#define IDM_SETPLATENOFROMHENT          32567
#define IDM_SETPLATENOFROMAGENT         32568

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        932
#define _APS_NEXT_COMMAND_VALUE         32572
#define _APS_NEXT_CONTROL_VALUE         1665
#define _APS_NEXT_SYMED_VALUE           863
#endif
#endif
