#ifndef __IMPORTEXPORTTASKS_H__
#define __IMPORTEXPORTTASKS_H__

enum IMPORTEXPORT_TASKS
{
	WRITE_PRCSNG_DOCS = 1000,
	WRITE_PRCSNG_RRIVS,
	WRITE_PRCSNG_HENTS,
	WRITE_PRCSNG_STOCKS,
	WRITE_WRITING_TO_FILE,
	READ_READING_HEADER,
	READ_PRCSNG_DOCS,
	READ_PRCSNG_HENTS,
	READ_PRCSNG_STOCKS,
	READ_PRCSNG_RRINVS,
	READ_PRCSNG_PASSIMGS,
	MERGING_STOCKS,
	MERGING_HENTS,
	FIND_DUPLICATES,
	MERGING_COWS,
	MERGING_DOCS,
	INSERTING_PASSIMGS,
	MERGING_INVOICES,
	INSERTING_DOCS,
	INSERTING_RRINVS,

};


#endif