#ifndef __HENTDATACOMPARATOR_H__
#define __HENTDATACOMPARATOR_H__

#include "RawData.h"
#include "Hent.h"
#include "RawDataComparator.h"

enum HENTDATA_MEMBERS
{
	HENTS_SORT_BY_NAME  = RAWDATA_MEMBER_BASE+1,
	HENTS_SORT_BY_ARIMRNO,
	HENTS_SORT_BY_ALIAS,
    HENTS_SORT_BY_STREET,
    HENTS_SORT_BY_POBOX,
    HENTS_SORT_BY_CITY,
    HENTS_SORT_BY_ZIP,
	HENTS_SORT_BY_PLATE,
	HENTS_SORT_BY_HENTTYPE,
	HENTS_SORT_BY_SYNCIT,
	HENTS_SORT_BY_COMBOITEM,
	HENTDATA_MEMBER_PHONE,
	HENTDATA_MEMBER_NIP,
	HENTDATA_MEMBER_WETNO,
	HENTDATA_MEMBER_EXTRAS,
	HENTDATA_MEMBER_COUNTRY,
	HENTDATA_MEMBER_PESEL,
	HENTDATA_MEMBER_REGON,
	HENTDATA_MEMBER_IDNO,
	HENTDATA_MEMBER_ISSUEDATE,
	HENTDATA_MEMBER_ISSUEPOST,
	HENTDATA_MEMBER_ACCOUNTNO,
	HENTDATA_MEMBER_BANKNAME,
	HENTDATA_MEMBER_WETLICENCENO,
	HENTDATA_MEMBER_CELLPHONENO,
	HENTDATA_MEMBER_EMAILADDRESS,
	HENTDATA_MEMBER_LATITUDE,
	HENTDATA_MEMBER_LONGITUDE,
};



class HentComparator : public RawDataComparator<Hent>
{
public:
	virtual COMPARE_RESULT CompareDataBy(UINT dataMember,Hent* DataLeft,Hent* DataRight);
};


#endif