//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by d:\cattlebase\cattlebase\Drawcli\res\DRAWCLI.rc
//
#define IDR_MANIFEST                    1
#define IDR_MAINFRAME                   2
#define IDR_DRAWCLTYPE                  3
#define IDR_DRAWCLTYPE_CNTR_IP          6
#define IDD_ABOUTBOX                    100
#define IDP_BUSY                        100
#define IDP_OLE_INIT_FAILED             101
#define IDD_PROP_RECT                   101
#define ID_WINDOWS_LIST                 101
#define IDP_FAILED_TO_CREATE            102
#define IDC_WEIGHT                      102
#define IDC_PENCIL                      102
#define IDC_NOFILL                      103
#define ID_POPUP_MENU                   103
#define IDC_WIDTH                       103
#define IDS_DEFAULTTEXT                 103
#define IDC_SPIN1                       104
#define IDD_SUMM_PAGE                   104
#define IDC_AUTHOR                      105
#define IDD_STAT_PAGE                   105
#define IDC_WSPIN                       105
#define IDC_KEYWORDS                    106
#define IDC_COMMENTS                    107
#define IDC_TITLE                       108
#define IDC_SUBJECT                     109
#define IDC_TEMPLATE                    110
#define IDC_SAVEDBY                     111
#define IDR_MENU_LW                     111
#define IDC_REVNUM                      112
#define IDI_ICON1                       112
#define IDC_EDITTIME                    113
#define IDC_LASTPRINT                   114
#define IDC_CREATEDATE                  115
#define IDC_LASTSAVE                    116
#define IDR_TOOLBAR_HELPER_ICONS        116
#define IDC_NUMPAGES                    117
#define IDC_GROUPLIST                   117
#define ID_SCPPV_PRINT                  118
#define IDC_NUMWORDS                    118
#define ID_SCPPV_NEXT                   119
#define IDC_NUMCHARS                    119
#define ID_SCPPV_PREV                   120
#define IDC_APPNAME                     120
#define ID_SCPPV_CLOSE                  121
#define ID_SCPPV_NUMPAGE                122
#define IDC_SECURITY                    122
#define ID_SCPPV_ZOOMIN                 123
#define IDC_THUMBNAIL                   123
#define ID_SCPPV_ZOOMOUT                124
#define IDC_BUTTON_COLOR_OUTLINE        124
#define IDC_BUTTON_COLOR_FILL           125
#define IDR_ABOUT                       125
#define IDC_STATIC1                     125
#define IDC_POSVERT                     125
#define IDC_STATIC2                     126
#define IDC_TEXT                        127
#define IDR_MENU_HELPER                 128
#define IDC_TEXTCOLOR                   128
#define IDR_241                         129
#define IDC_CHOOSEFONT                  129
#define IDD_PROP_TEXT                   131
#define IDC_LABELEDIT                   131
#define IDB_NULLIMAGE                   132
#define IDC_EDIT1                       132
#define IDC_GROUPNAME                   132
#define IDC_STYLENAME                   132
#define IDD_PROP_POS                    133
#define IDC_EDIT2                       133
#define IDC_LEFTEDIT                    133
#define IDC_EDIT3                       134
#define IDC_TOPEDIT                     134
#define IDC_EDIT4                       135
#define IDC_RIGHTEDIT                   135
#define IDC_EDIT5                       136
#define IDC_BOTTOMEDIT                  136
#define IDC_FONT                        137
#define IDC_ITALIC                      138
#define IDC_UNDERLINE                   139
#define IDD_GROUPPOS                    139
#define IDC_STRIKEOUT                   140
#define IDD_GROUPMGR                    140
#define IDD_OBJGROUP                    141
#define IDD_IMGOPEN                     142
#define IDC_HEIGHT                      143
#define IDC_HSPIN                       144
#define IDB_TEXT_TBA                    145
#define IDB_TEXT_TBAR                   145
#define IDD_STYLEMGR                    146
#define IDD_PROP_FIG                    147
#define IDR_ACCELERATOR1                148
#define IDR_GRPMGRACCEL                 148
#define IDD_DIALOG1                     149
#define IDD_STYLE                       149
#define IDC_RIGHTSPIN                   150
#define IDC_TOPSPIN                     151
#define IDC_BOTTOMSPIN                  152
#define IDC_LEFTSPIN                    153
#define IDC_HORZ                        156
#define IDC_VERT                        158
#define IDC_POSHORZ                     159
#define IDC_GROUPS                      160
#define IDC_GROUPADD                    161
#define IDC_GROUPDEL                    162
#define IDC_OPENIMG                     163
#define IDC_GROUPMGR                    165
#define IDC_BOLD                        166
#define IDC_RADIO1                      167
#define IDC_RADIO2                      168
#define IDC_RADIO3                      169
#define IDC_RADIO4                      170
#define IDC_STYLEEDIT                   172
#define IDC_STYLEDEL                    173
#define IDC_STYLELIST                   174
#define IDC_STYLECOLOR                  175
#define IDC_STYLEFONT                   176
#define IDC_NEWSTYLE                    185
#define IDC_STYLECOMBO                  186
#define IDC_NOTOWNSTYLE                 187
#define IDC_GRPHORALIGN                 188
#define IDC_GRPVERALIGN                 189
#define IDC_VERCOMBO                    192
#define IDC_HORCOMBO                    193
#define IDC_ORIENTATION                 195
#define IDC_HALIGN                      196
#define IDC_VALIGN                      197
#define IDC_ROUNDX                      198
#define IDC_ROUNDY                      199
#define IDC_ROUNDNES                    200
#define ID_OBJECT_MOVETOFRONT           501
#define ID_OBJECT_MOVETOBACK            502
#define ID_OBJECT_MOVEFORWARD           503
#define ID_OBJECT_MOVEBACK              504
#define IDC_THEME_2000                  2017
#define IDC_THEME_XP                    2018
#define IDC_THEME_2003                  2019
#define ID_VIEW_LIKE_STUDIO_2005        2298
#define ID_CANCEL_EDIT                  32768
#define ID_VIEW_GRID                    32769
#define ID_DRAW_SELECT                  32770
#define ID_DRAW_LINE                    32771
#define ID_DRAW_RECT                    32772
#define ID_DRAW_ROUNDRECT               32773
#define ID_DRAW_ELLIPSE                 32774
#define ID_OBJECT_LINECOLOR             32775
#define ID_OBJECT_FILLCOLOR             32776
#define ID_VIEW_PAPERCOLOR              32781
#define ID_DRAW_POLYGON                 32782
#define ID_VIEW_SHOWOBJECTS             32784
#define ID_EDIT_PROPERTIES              32785
#define ID_FILE_SUMMARYINFO             32792
#define ID_VIEW_MENUBAR                 32812
#define ID_LINE_WIDTH_0                 32814
#define ID_LINE_WIDTH_1                 32815
#define ID_LINE_WIDTH_2                 32816
#define ID_LINE_WIDTH_3                 32817
#define ID_LINE_WIDTH_4                 32818
#define ID_LINE_WIDTH_5                 32819
#define ID_LINE_WIDTH_6                 32820
#define ID_LINE_WIDTH_7                 32821
#define ID_LINE_WIDTH_8                 32822
#define ID_LINE_WIDTH_9                 32823
#define ID_LINE_WIDTH_10                32824
#define ID_LINE_WIDTH_OTHER             32825
#define ID_DOC_LINE_WIDTH               32826
#define ID_VIEW_TOOLBAR2                32827
#define ID_MDITABS_TOP                  32829
#define ID_MDITABS_BOTTOM               32830
#define ID_MDITABS_LEFT                 32831
#define ID_MDITABS_RIGHT                32832
#define ID_MDITABS_SHOW_CLOSE           32833
#define ID_MDITABS_SHOW_CTX_HELP        32834
#define ID_UISTYLE_2000                 32835
#define ID_UISTYLE_XP                   32836
#define ID_VIEW_PALETTE                 32838
#define ID_VIEW_LIKE_OFFICE_2003        32839
#define ID_ALIGNLEFTS                   32844
#define ID_ALIGNTOPS                    32846
#define ID_GROUPPOS                     32848
#define ID_ADDTOGROUP                   32850
#define ID_SELECTGROUP                  32852
#define ID_SHOWGROUPMGR                 32855
#define ID_MAKESAMESIZE                 32857
#define ID_NEIGHBOURS                   32858
#define ID_MAKESAMESIZE_WIDTH           32859
#define ID_MAKESAMESIZE_HEIGHT          32860
#define ID_MAKESAMESIZE_BOTH            32861
#define ID_TOPBOTTOM                    32865
#define ID_LEFTRIGHT                    32866
#define ID_SHOW_STYLEMANAGER            32868
#define IDA_DELGROUP                    32869
#define ID_CUSTOMIZE                    32894
#define ID_DRAW_TEXT                    32895
#define ID_DRAW_IMAGE                   32896
#define IDS_STRING_NO_COLOR_FILL        44004
#define IDS_STRING_NO_COLOR_OUTLINE     44005
#define IDR_TOOLBAR_ZOOM                44006
#define ID_MYEXTBTN_SLIDER              44007
#define IDS_PANE_ZOOM                   44008
#define IDS_PANE_POS                    44009
#define IDS_PANE_SIZE                   44010
#define ID_NEW_PAGE                     44011
#define ID_NEXT_PAGE                    44012
#define ID_PREV_PAGE                    44013
#define ID_DEL_PAGE                     44014
#define ID_GRID                         44015
#define ID_BACKDOC                      44016
#define ID_OPENBACKIMG                  44017
#define IDB_NULLIMG                     44018

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        150
#define _APS_NEXT_COMMAND_VALUE         32871
#define _APS_NEXT_CONTROL_VALUE         201
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
