#if !defined(_OCRCFG__INCLUDED_)
#define _OCRCFG__INCLUDED_
#define __OCRCFG_FIRST_RUN__	
#endif

#if defined(__OCRCFG_FIRST_RUN__)
#define	__INCLUDE_OCRCFGDEF__
#elif defined(__CFG_IMPLEMENTATION__)
#define	__INCLUDE_OCRCFGDEF__
#endif

#if defined(__INCLUDE_OCRCFGDEF__)
#include "cfg\Cfg.h"

BEGIN_CFGDEF(OCRCFG)


		CFG_SECTION(CFGID_PASSPORTRECOGNIZERDATASETTINGSSECTION,"PASSPORTRECOGNIZERDATASETTINGS")
			CFG_ITEM(CFG_UPPERCASEHENTDATAITEM,1,"UPPERCASEHENTDATA")					
					CFG_BOOL(CFG_UPPERCASEHENTDATA,TRUE)

			CFG_ITEM(CFG_DEFAULTSTOCKIDITEM,1,"DEFAULTSTOCKID")
					CFG_NUM(CFG_DEFAULTSTOCKID,0)

			CFG_ITEM(CFG_USEDEFAULTSTOCKITEM,1,"USEDEFAULTSTOCK")
					CFG_BOOL(CFG_USEDEFAULTSTOCK,FALSE)

			CFG_ITEM(CFG_NOUPDATEIFPRESENTITEM,1,"NOUPDATEIFPRESENT")
					CFG_BOOL(CFG_NOUPDATEIFPRESENT,TRUE)

			CFG_ITEM(CFG_INPUTPASSDATEITEM,1,"PASSDATE")
					CFG_BOOL(CFG_INPUTPASSDATE,TRUE)

			CFG_ITEM(CFG_INPUTBIRTHITEM,1,"BIRTH")
					CFG_BOOL(CFG_INPUTBIRTH,TRUE)			

			CFG_ITEM(CFG_INPUTMOTHEREANITEM,1,"MOTHEREAN")
					CFG_BOOL(CFG_INPUTMOTHEREAN,TRUE)

			CFG_ITEM(CFG_INPUTFSTOWNRADRITEM,1,"FSTOWNRADR")
					CFG_BOOL(CFG_INPUTFSTOWNRADR,TRUE)

			CFG_ITEM(CFG_INPUTPASSNOITEM,1,"PASSNO")
					CFG_BOOL(CFG_INPUTPASSNO,TRUE)

			CFG_ITEM(CFG_INPUTSEXITEM,1,"SEX")
					CFG_BOOL(CFG_INPUTSEX,TRUE)			

			CFG_ITEM(CFG_INPUTSTOCKITEM,1,"STOCK")
					CFG_BOOL(CFG_INPUTSTOCK,TRUE)

		CFG_SECTION(CFGID_PASSPORTRECOGNIZERSCANNERSETTINGSSECTION,"PASSPORTRECOGNIZERSCANNERSETTINGS")
			CFG_ITEM(CFG_BRIGHTNESSITEM,1,"BRIGHTNESS")
					CFG_NUM(CFG_BRIGHTNESS,0)		

			CFG_ITEM(CFG_CONTRASTITEM,1,"CONTRAST")
					CFG_NUM(CFG_CONTRAST,0)			

			CFG_ITEM(CFG_RESOLUTIONITEM,1,"RESOLUTION")
					CFG_NUM(CFG_RESOLUTION,300)					
					
			
		CFG_SECTION(CFGID_PASSPORTRECOGNIZERIMAGESETTINGSSECTION,"PASSPORTRECOGNIZERIMAGESETTINGS")	
			CFG_ITEM(CFG_BLACKLEVELITEM,1,"BLACKLEVEL")
					CFG_NUMLIMIT(CFG_BLACKLEVEL,128,210,190)

			CFG_ITEM(CFG_CENTERITEM,1,"CENTER")
					CFG_NUMLIMIT(CFG_CENTER,0,255,255)

			CFG_ITEM(CFG_SIGMAITEM,1,"SIGMA")
					CFG_NUMLIMIT(CFG_SIGMA,1,510,128)	

			CFG_ITEM(CFG_DOPALENHANCEITEM,1,"DOPALENHANCEITEM")
					CFG_BOOL(CFG_DOPALENHANCE,FALSE)					

		CFG_SECTION(CFGID_PASSPORTRECOGNIZERENGINESETTINGSSECTION,"PASSPORTRECOGNIZERENGINESETTINGS")
			CFG_ITEM(CFG_ENGINEPATHITEM,1,"ENGINEPATH")
					CFG_STRING(CFG_ENGINEPATH,"")

			CFG_ITEM(CFG_LICENSEFILEPATHITEM,1,"LICENSEFILEPATH")
					CFG_STRING(CFG_LICENSEFILEPATH,"")	

			CFG_ITEM(CFG_DEVELOPERSNITEM,1,"DEVELOPERSN")
					CFG_STRING(CFG_DEVELOPERSN,"")	

			CFG_ITEM(CFG_PROJECTIDITEM,1,"PROJECTID")
					CFG_STRING(CFG_PROJECTID,"")	
		
			
	END_CFGDEF

#endif


#if defined(__OCRCFG_FIRST_RUN__)

#include "PassportRecognizerSettings.h"

class PassportRecognizerSettingsStorage 
{
public:
	PassportRecognizerSettingsStorage();
	~PassportRecognizerSettingsStorage();
	void Save(PassportRecognizerSettings& settings);
	void Load(PassportRecognizerSettings& settings);
private:
	void SaveDataSettings(const DataSettings& dataSettings);
	void SaveEngineSettings(const EngineSettings& engineSettings);
	void SaveImageSettings(const ImageSettings& imageSettings); 
	void SaveScannerSettings(const ScannerSettings& scanerSettings);

	void LoadDataSettings(DataSettings& dataSettings);
	void LoadEngineSettings(EngineSettings& engineSettings);
	void LoadImageSettings(ImageSettings& imageSettings); 
	void LoadScannerSettings(ScannerSettings& scanerSettings);
private:
	CCfg m_storage;
};



#endif

#undef __INCLUDE_OCRCFGDEF__
#undef __OCRCFG_FIRST_RUN__
#undef __CFG_IMPLEMENTATION__