
#ifndef _UNICODE
#define VC_EXTRALEAN
#endif

#define _SECURE_ATL 1

#include <afxwin.h>         // MFC core and standard components
#include <afxext.h>         // MFC extensions (including VB)
#include <afxole.h>         // MFC OLE 2.0 support
#include <afxodlgs.h>       // MFC OLE 2.0 dialog support
#include <afxcmn.h>         // MFC common control support
#include <afxpriv2.h>


#define YAXISRISESUP

#if (!defined __PROF_UIS_H)
	#include <Prof-UIS.h>
#endif // (!defined __PROF_UIS_H)
