#include "stdafx.h"
#include "LoadTaskTranslator.h"
#include "../CattleSQL.h"
#ifdef _DEBUG
#define new DEBUG_NEW
#undef THIS_FILE
static char THIS_FILE[] = __FILE__;
#endif



const UINT LoadTaskTranslator::LoadingDBTaskId2TaskName[][2] =
{
	{CattleSQL::LOADING_REASONS,IDS_LOADING_REASONS},
	{CattleSQL::LOADING_HENTTYPES,IDS_LOADING_HENTTYPES},
	{CattleSQL::LOADING_COUNTRIES,IDS_LOADING_COUNTRIES},
	{CattleSQL::LOADING_HENTS,IDS_LOADING_HENTS},
	{CattleSQL::LOADING_STOCKS,IDS_LOADING_STOCKS},
	{CattleSQL::LOADING_INDOCS,IDS_LOADING_INDOCS},
	{CattleSQL::LOADING_OUTDOCS,IDS_LOADING_OUTDOCS},
	{CattleSQL::LOADING_RULES,IDS_LOADING_RULES},
	{CattleSQL::LOADING_INVOICES,IDS_LOADING_INVOICES},
	{CattleSQL::LOADING_COWS,IDS_LOADING_COWS},
	{CattleSQL::LOADING_USERS,IDS_LOADING_USERS},
	{CattleSQL::LOADING_EXPENSES,IDS_LOADING_EXPENSES},
	{CattleSQL::LOADING_EXPENSECATEGORIES,IDS_LODING_EXPENSECATEGORIES},
	{CattleSQL::LOADING_PRICES,IDS_LOADINGCOWPRICES},
	{CattleSQL::MERGING_VATBUYINVOICES,IDS_MERGING_BUYINVS},
	{CattleSQL::MERGING_VATSELLINVOICES,IDS_MERGING_SELLINVS},
	{0,0}
};


LoadTaskTranslator::LoadTaskTranslator()
{
	for(const UINT *tasks = LoadingDBTaskId2TaskName[0];
		tasks[0] && tasks[1];tasks += 2)
	{
		Add(tasks[0],tasks[1]);		
	}
}

