#if !defined(_PRINTCFG__INCLUDED_)
#define _PRINTCFG__INCLUDED_
#define __PRINTCFG_FIRST_RUN__	
#endif

#if defined(__PRINTCFG_FIRST_RUN__)
#define	__INCLUDE_PRINTCFGDEF__
#elif defined(__CFG_IMPLEMENTATION__)
#define	__INCLUDE_PRINTCFGDEF__
#endif

#if defined(__INCLUDE_PRINTCFGDEF__)
#include "cfg\Cfg.h"

/*
	This file must be #included twice from the CCfg derived class, once to enumerate
	the ID's (definition) and once to implement the array of CFGDEF structures (declaration).
	The CFG_... macros are redefined when __CFG_IMPLEMENTATION__ is defined.

	When this file is included from the CCfg derived class and __CFG_IMPLEMENTATOIN__
	is defined the following macros generate the array of CFGDEF structures used to
	access the cfg file.

	When this file is included without __CFG_IMPLEMENTATION__ defined (the first time
	it is included in the CCfg derived class and whenever it is included in another 
	cpp file) all ID's are enumerated to generate unique numbers for all cfg ID's.
*/

#define PRINTDOC_CFG_ITEM_ARGNUM(doccfgname,argnum) CFG_ITEM(CFGID_##doccfgname,argnum,#doccfgname) \
											CFG_NUM(CFGID_##doccfgname##_OFFX,0) \
											CFG_NUM(CFGID_##doccfgname##_OFFY,0) \
											CFG_STRING(CFGID_##doccfgname##_FONTFAMILY,"Arial CE") \
											CFG_NUM(CFGID_##doccfgname##_FONTHEIGHT,28) \
											CFG_NUM(CFGID_##doccfgname##_COWSSORTBY,-1) \
											CFG_BOOL(CFGID_##doccfgname##_SORTORDER,FALSE) \
											CFG_NUM(CFGID_##doccfgname##_MONEYDECIMALPT,'.') \
											CFG_NUM(CFGID_##doccfgname##_MONEYPRECISION,2) \
											CFG_NUM(CFGID_##doccfgname##_WEIGHTDECIMALPT,'.') \
											CFG_NUM(CFGID_##doccfgname##_WEIGHTPRECISION,3) 
											

#define PRINTDOC_CFG_ITEM(doccfgname)  PRINTDOC_CFG_ITEM_ARGNUM(doccfgname,10)

#define PRINTDOC_CFG_ITEM_ZGL(doccfgname) PRINTDOC_CFG_ITEM_ARGNUM(doccfgname,13) \
											CFG_BOOL(CFGID_##doccfgname##_USE_CUSTOM_EVENTS,FALSE) \
											CFG_NUM(CFGID_##doccfgname##_CUSTOM_EVENTS,0) \
											CFG_BOOL(CFGID_##doccfgname##_DONTFILLDSTHENTNO,FALSE)

#define PRINTDOC_CFG_ITEM_INVOICE(doccfgname) PRINTDOC_CFG_ITEM_ARGNUM(doccfgname,19) \
											  CFG_STRING(CFGID_##doccfgname##_PKWIU,"01.2") \
											  CFG_STRING(CFGID_##doccfgname##_NAZWALICZEB1,"cielê") \
				                              CFG_STRING(CFGID_##doccfgname##_NAZWALICZEB2_4,"cielêta") \
				                              CFG_STRING(CFGID_##doccfgname##_NAZWALICZEBPOZOST,"ciel¹t") \
											  CFG_STRING(CFGID_##doccfgname##_INVTITLE,"FAKTURA") \
											  CFG_STRING(CFGID_##doccfgname##_INVEXTRASTEMPL,"") \
											  CFG_STRING(CFGID_##doccfgname##_INVENTRYFORMAT,"") \
											  CFG_NUM(CFGID_##doccfgname##_PRICEPERKGDECIMALPT,'.') \
											  CFG_NUM(CFGID_##doccfgname##_PRICEPERKGPRECISION,3) 




BEGIN_CFGDEF(PRINTCFG)

	CFG_SECTION(CFGID_PRINTDOCSOPT,"PrintDocsOpt")
	
		PRINTDOC_CFG_ITEM_ARGNUM(WETBOOK,11)
			CFG_NUM(CFGID_WETBOOK_LP,1)

		PRINTDOC_CFG_ITEM_ARGNUM(INDOCS,12)
			CFG_BOOL(CFGID_INDOCS_PRINTEXTRAS,TRUE) 		
			CFG_BOOL(CFGID_INDOCS_USEINVWEIGHT,TRUE) 		

		PRINTDOC_CFG_ITEM_ARGNUM(OUTDOCS,12)
			CFG_BOOL(CFGID_OUTDOCS_PRINTEXTRAS,TRUE)
			CFG_BOOL(CFGID_OUTDOCS_USEINVWEIGHT,TRUE) 		

		
		PRINTDOC_CFG_ITEM_ARGNUM(RAPORT,12)
			CFG_NUM(CFGID_RAPORT_PAGENUM,1) 
			CFG_NUM(CFGID_RAPORT_SERIALNUM,1)


		PRINTDOC_CFG_ITEM_ZGL(PZZGL60DO)
		PRINTDOC_CFG_ITEM_ZGL(WZZGL60Z)
		PRINTDOC_CFG_ITEM_ZGL(PZZGL30DO)
		PRINTDOC_CFG_ITEM_ZGL(WZZGL30Z)
		PRINTDOC_CFG_ITEM_ZGL(PZZGLPOCZTDO)
		PRINTDOC_CFG_ITEM_ZGL(WZZGLPOCZTZ)			
		PRINTDOC_CFG_ITEM_ZGL(BUYINVZGL60DO)
		PRINTDOC_CFG_ITEM_ZGL(BUYINVZGL30DO)
		PRINTDOC_CFG_ITEM_ZGL(BUYINVZGLPOCZTDO)
		PRINTDOC_CFG_ITEM_ZGL(SELLINVZGL60Z)
		PRINTDOC_CFG_ITEM_ZGL(SELLINVZGL30Z)
		PRINTDOC_CFG_ITEM_ZGL(SELLINVZGLPOCZTZ)

		PRINTDOC_CFG_ITEM_INVOICE(FAKRRWEIGHT)
		PRINTDOC_CFG_ITEM_INVOICE(FAKRR3WEIGHT)

		PRINTDOC_CFG_ITEM_INVOICE(BUYFAKVAT)
		PRINTDOC_CFG_ITEM_INVOICE(SELLFAKVAT)

		PRINTDOC_CFG_ITEM_INVOICE(BUYFAKVATGRP)
		PRINTDOC_CFG_ITEM_INVOICE(SELLFAKVATGRP)
		
		PRINTDOC_CFG_ITEM(SWIADZDR)
		PRINTDOC_CFG_ITEM(PRZELEW)
		PRINTDOC_CFG_ITEM(ZBRPOLPRZEL)
		PRINTDOC_CFG_ITEM(ZESTFAKKUPNA)
		PRINTDOC_CFG_ITEM(ZESTFAKSPRZ)

		PRINTDOC_CFG_ITEM_ARGNUM(IDPZ,11)
			CFG_STRING(CFGID_IDPZ_SPIECIES,"")
		
		PRINTDOC_CFG_ITEM_INVOICE(BUYFAKVAT_ZESPSZT)
		PRINTDOC_CFG_ITEM_INVOICE(SELLFAKVAT_ZESPSZT)
		
		PRINTDOC_CFG_ITEM_ARGNUM(SPECFAKWEW,12)
		  CFG_NUM(CFGID_SPECFAKWEW_PRICEPERKGDECIMALPT,'.')
		  CFG_NUM(CFGID_SPECFAKWEW_PRICEPERKGPRECISION,5) 
		
		PRINTDOC_CFG_ITEM(PASS)

		PRINTDOC_CFG_ITEM_ARGNUM(DEZYNFWZ,12)
			CFG_BOOL(CFGID_DEZYNFWZ_DONTFILLPLATENO,FALSE)
			CFG_STRING(CFGID_DEZYNFWZ_AGENTNAME,"")
		
		PRINTDOC_CFG_ITEM_ARGNUM(DEZYNFPZ,12)
			CFG_BOOL(CFGID_DEZYNFPZ_DONTFILLPLATENO,FALSE)
			CFG_STRING(CFGID_DEZYNFPZ_AGENTNAME,"")
	
		
		PRINTDOC_CFG_ITEM_INVOICE(BUYFAKVATGRPWGHT)
		PRINTDOC_CFG_ITEM_INVOICE(SELLFAKVATGRPWGHT)
		
		PRINTDOC_CFG_ITEM(SOKOLOW)		
		
		PRINTDOC_CFG_ITEM(OSWIADFPWM)
		
		PRINTDOC_CFG_ITEM_INVOICE(FAKRRPIECE)
		PRINTDOC_CFG_ITEM_INVOICE(FAKRR3PIECE)
		
		PRINTDOC_CFG_ITEM(EXPENSESSUM)
		PRINTDOC_CFG_ITEM(IDPZBC)
		PRINTDOC_CFG_ITEM(HENTLBL)
		PRINTDOC_CFG_ITEM(INDOCHENTLBL)
		PRINTDOC_CFG_ITEM(INVHENTLBL)
		PRINTDOC_CFG_ITEM(OUTDOCHENTLBL)
		
		PRINTDOC_CFG_ITEM_INVOICE(FAKRRTERM3WEIGHT)
		PRINTDOC_CFG_ITEM_INVOICE(FAKRRTERM3PIECE)
		

		PRINTDOC_CFG_ITEM_ARGNUM(TRANSPORTINDOC,12)
			CFG_BOOL(CFGID_TRANSPORTINDOC_DONOTFILLCARRIER,FALSE) 		
			CFG_STRING(CFGID_TRANSPORTINDOC_TEST,"dick test in") 		
			
			
		PRINTDOC_CFG_ITEM_ARGNUM(TRANSPORTOUTDOC,12)
			CFG_BOOL(CFGID_TRANSPORTOUTDOC_DONOTFILLCARRIER,FALSE) 		
			CFG_STRING(CFGID_TRANSPORTOUTDOC_TEST,"dick test out") 		
		
		PRINTDOC_CFG_ITEM_ARGNUM(KSIEGASTADA,12)
			CFG_NUM(CFGID_KSIEGASTADA_PAGENUM,1) 
			CFG_NUM(CFGID_KSIEGASTADA_SERIALNUM,1)
		
		PRINTDOC_CFG_ITEM_ARGNUM(SPECFAKZEW,12)
		  CFG_NUM(CFGID_SPECFAKZEW_PRICEPERKGDECIMALPT,'.')
		  CFG_NUM(CFGID_SPECFAKZEW_PRICEPERKGPRECISION,5) 

		PRINTDOC_CFG_ITEM_INVOICE(BUYFAKVAT_ZESPWAGA)
		PRINTDOC_CFG_ITEM_INVOICE(SELLFAKVAT_ZESPWAGA)

		PRINTDOC_CFG_ITEM_INVOICE(BUYINVVATGRPPRICEPIECE)
		PRINTDOC_CFG_ITEM_INVOICE(SELLINVVATGRPPRICEPIECE)

		PRINTDOC_CFG_ITEM(WEIGHTINGINDOC)
		PRINTDOC_CFG_ITEM(WEIGHTINGOUTDOC)

		PRINTDOC_CFG_ITEM_INVOICE(BUYINVVATGRPPRICEWEIGHT)
		PRINTDOC_CFG_ITEM_INVOICE(SELLINVVATGRPPRICEWEIGHT)

		PRINTDOC_CFG_ITEM(NORMALIZEFOODCHAINRRINV)

		PRINTDOC_CFG_ITEM(REGISTRACTION)			
			
END_CFGDEF

#endif


#if defined(__PRINTCFG_FIRST_RUN__)

class CPrintCfg : public CCfg  
{
private:
	CPrintCfg();
public:

	enum PRINTDOC_CFG_ITEM_INDEX
	{
		CFG_OFFX = 0,
		CFG_OFFY,
		CFG_FONTFAMILY,
		CFG_FONTHEIGHT,
		CFG_COWSSORTBY,
		CFG_SORTORDER,
		CFG_MONEYDECIMALPT,
		CFG_MONEYPRECISION,
		CFG_WEIGHTDECIMALPT,
		CFG_WEIGHTPRECISION,		

		CFG_PRINT_OPTION_MAX
	};

	virtual ~CPrintCfg();
	static CPrintCfg m_printCfg;
};

#define PrintCfg() (CPrintCfg::m_printCfg)

#endif

#undef __INCLUDE_PRINTCFGDEF__
#undef __PRINTCFG_FIRST_RUN__
#undef __CFG_IMPLEMENTATION__