#include "stdafx.h"
#include "printdocs.h"
#include "WetBook.h"
#include "PzWzDoc.h"
#include "herdbook/raportARiMR.h"
#include "herdbook/KsiegaStada.h"
#include "invoice/InvoiceDoc.h"
#include "invoice/InvoiceDocOptionsDlg.h"
#include "swiadzdrowia.h"
#include "przelew.h"
#include "zbiorczepolecenie.h"
#include "zbiorowkafv.h"
#include "idpz.h"
#include "PrintDocsCfg.h"
#include "PassPrint.h"
#include "dezynfekcja.h"
#include "SokolowDoc.h"
#include "oswiadczenieFPMW.h"
#include "ExpensesSummary.h"
#include "DYMOBaseHentLabel.h"
#include "DYMODocHentLabel.h"
#include "DYMOInvoiceHentLabel.h"
#include "TransportDoc.h"
#include "WeightingDoc.h"
#include "notification/Notifications.h"
#include "NormalizeFoodChain.h"
#include "registraction/RegistrationDuplex.h"

#include "invoicedetails/InvoiceDetailsInternal.h"
#include "invoicedetails/InvoiceDetailsExternal.h"
#include "invoicedetails/InvoiceDetailsOptionsDlg.h"

#include "../printing/CowDrwDocView.h"
#include "../printing/DYMODocView.h"

const PRINTDOCS g_PrintDocs[] =
{
	{ID_DOC_HENTDYMOLABEL,				IDS_DOCNAME_DYMOHENTLABEL,			RUNTIME_CLASS(CDYMOBaseHentLabel),					"HENTLABEL",			DATATYPE_HENTS,			CFGID_HENTLBL,					NULL,										RUNTIME_CLASS(CDYMODocView),   false}, 
	{ID_DOC_INDOCHENTDYMOLABEL,			IDS_DOCNAME_DYMOHENTLABEL,			RUNTIME_CLASS(CDYMODocHentLabel),					"HENTLABEL",			DATATYPE_INDOCS,		CFGID_INDOCHENTLBL,				NULL,										RUNTIME_CLASS(CDYMODocView),   false},
	{ID_DOC_OUTDOCHENTDYMOLABEL,		IDS_DOCNAME_DYMOHENTLABEL,			RUNTIME_CLASS(CDYMODocHentLabel),					"HENTLABEL",			DATATYPE_OUTDOCS,		CFGID_OUTDOCHENTLBL,			NULL,										RUNTIME_CLASS(CDYMODocView),   false}, 
	{ID_DOC_INVHENTDYMOLABEL,			IDS_DOCNAME_DYMOHENTLABEL,			RUNTIME_CLASS(CDYMOInvoiceHentLabel),				"HENTLABEL",			DATATYPE_INVS,			CFGID_INVHENTLBL,				NULL,										RUNTIME_CLASS(CDYMODocView),   false}, 
	{ID_DOC_WETBOOK,					IDS_DOCNAME_WETBOOK,				RUNTIME_CLASS(CWetBookDoc),							"WETBOOK",				DATATYPE_COWS,			CFGID_WETBOOK,					RUNTIME_CLASS(CWetBookOptDlg),				RUNTIME_CLASS(CCowDrwDocView), false}, 
	{ID_DOC_INDOCS,						IDS_DOCNAME_INDOCS,					RUNTIME_CLASS(CPzDoc),								"PZWZ",					DATATYPE_INDOCS,		CFGID_INDOCS,					RUNTIME_CLASS(CPzWzOptDlg),					RUNTIME_CLASS(CCowDrwDocView), true}, 
	{ID_DOC_OUTDOCS,					IDS_DOCNAME_OUTDOCS,				RUNTIME_CLASS(CWzDoc),								"PZWZ",					DATATYPE_OUTDOCS,		CFGID_OUTDOCS,					RUNTIME_CLASS(CPzWzOptDlg),					RUNTIME_CLASS(CCowDrwDocView), true}, 
	{ID_DOC_RAPORT,						IDS_DOCNAME_RAPORT,					RUNTIME_CLASS(CRaportARiMR),						"RAPORT",				DATATYPE_COWS,			CFGID_RAPORT,					RUNTIME_CLASS(CHerdBookOptDlg),				RUNTIME_CLASS(CCowDrwDocView), true}, 
	
	{ID_DOC_BUYVATINVOICE,				IDS_DOCNAME_VATINVOICE,				RUNTIME_CLASS(CFakturaVATA4),						"FAKTURAVAT",			DATATYPE_BUYVATINVS,	CFGID_BUYFAKVAT,				RUNTIME_CLASS(CInvoiceDocOptionsDlg),		RUNTIME_CLASS(CCowDrwDocView), true}, 
	{ID_DOC_SELLVATINVOICE,				IDS_DOCNAME_VATINVOICE,				RUNTIME_CLASS(CFakturaVATA4),						"FAKTURAVAT",			DATATYPE_SELLVATINVS,	CFGID_SELLFAKVAT,				RUNTIME_CLASS(CInvoiceDocOptionsDlg),		RUNTIME_CLASS(CCowDrwDocView), true}, 

	{ID_DOC_BUYVATINVGRPPIECE,			IDS_DOCNAME_VATINVGRPPIECE,			RUNTIME_CLASS(CFakturaVATGroupPieceA4),				"FAKTURAVAT",			DATATYPE_BUYVATINVS,	CFGID_BUYFAKVATGRP,				RUNTIME_CLASS(CInvoiceDocOptionsDlg),		RUNTIME_CLASS(CCowDrwDocView), false}, 
	{ID_DOC_SELLVATINVGRPPIECE,			IDS_DOCNAME_VATINVGRPPIECE,			RUNTIME_CLASS(CFakturaVATGroupPieceA4),				"FAKTURAVAT",			DATATYPE_SELLVATINVS,	CFGID_SELLFAKVATGRP,			RUNTIME_CLASS(CInvoiceDocOptionsDlg),		RUNTIME_CLASS(CCowDrwDocView), false}, 

	{ID_DOC_SWIADZDR,					IDS_DOCNAME_SWIADZDR,				RUNTIME_CLASS(CHealthCertDoc),						"SWIADZDROWIA",			DATATYPE_OUTDOCS,		CFGID_SWIADZDR,					NULL,										RUNTIME_CLASS(CCowDrwDocView), true}, 
	{ID_DOC_PRZELEW,					IDS_DOCNAME_PRZELEW,				RUNTIME_CLASS(CPrzelewDoc),							"PRZELEW",				DATATYPE_INVS,			CFGID_PRZELEW,					NULL,										RUNTIME_CLASS(CCowDrwDocView),  false}, 
	{ID_DOC_ZBRPOLPRZEL,				IDS_DOCNAME_ZBRPOLPRZEL,			RUNTIME_CLASS(CZbiorczePolecenieDoc),				"ZBIORCZEPOLECENIE",	DATATYPE_INVS,			CFGID_ZBRPOLPRZEL,				NULL,										RUNTIME_CLASS(CCowDrwDocView), false}, 
	{ID_DOC_ZESTFAKKUPNA,				IDS_DOCNAME_ZESTFAKKUPNA,			RUNTIME_CLASS(CZbiorowkaFVBuyDoc),					"ZBIOROWKAFV",			DATATYPE_BUYINVS,		CFGID_ZESTFAKKUPNA,				NULL,										RUNTIME_CLASS(CCowDrwDocView), false}, 
	{ID_DOC_ZESTFAKSPRZ,				IDS_DOCNAME_ZESTFAKSPRZ,			RUNTIME_CLASS(CZbiorowkaFVSellDoc),					"ZBIOROWKAFV",			DATATYPE_SELLINVS,		CFGID_ZESTFAKSPRZ,				NULL,										RUNTIME_CLASS(CCowDrwDocView), false}, 
	{ID_DOC_IDPZ,						IDS_DOCNAME_IDPZ,					RUNTIME_CLASS(CCowTransInfoDoc),					"IDPZ",					DATATYPE_OUTDOCS,		CFGID_IDPZ,						RUNTIME_CLASS(CTransInfoDocOptDlg),			RUNTIME_CLASS(CCowDrwDocView), true}, 
	
	{ID_DOC_BUYVATINVCOMPACTPIECE,		IDS_DOCNAME_VATINVCOMPACTPIECE,		RUNTIME_CLASS(CFakturaVATCompactPieceA4),			"FAKTURAVAT",			DATATYPE_BUYVATINVS,	CFGID_BUYFAKVAT_ZESPSZT,		RUNTIME_CLASS(CInvoiceDocOptionsDlg),		RUNTIME_CLASS(CCowDrwDocView), false}, 
	{ID_DOC_SELLVATINVCOMPACTPIECE,		IDS_DOCNAME_VATINVCOMPACTPIECE,		RUNTIME_CLASS(CFakturaVATCompactPieceA4),			"FAKTURAVAT",			DATATYPE_SELLVATINVS,	CFGID_SELLFAKVAT_ZESPSZT,		RUNTIME_CLASS(CInvoiceDocOptionsDlg),		RUNTIME_CLASS(CCowDrwDocView), false}, 

	{ID_DOC_BUYVATINVCOMPACTWEIGHT,		IDS_DOCNAME_VATINVCOMPACTWEIGHT,	RUNTIME_CLASS(CFakturaVATCompactWeightA4),			"FAKTURAVAT",			DATATYPE_BUYVATINVS,	CFGID_BUYFAKVAT_ZESPWAGA,		RUNTIME_CLASS(CInvoiceDocOptionsDlg),		RUNTIME_CLASS(CCowDrwDocView), false},
	{ID_DOC_SELLVATINVCOMPACTWEIGHT,	IDS_DOCNAME_VATINVCOMPACTWEIGHT,	RUNTIME_CLASS(CFakturaVATCompactWeightA4),			"FAKTURAVAT",			DATATYPE_SELLVATINVS,	CFGID_SELLFAKVAT_ZESPWAGA,		RUNTIME_CLASS(CInvoiceDocOptionsDlg),		RUNTIME_CLASS(CCowDrwDocView), false}, 
	
	{ID_DOC_SPECFAKWEW,					IDS_DOCNAME_SPECFAKWEW,				RUNTIME_CLASS(CInvoiceDetailsInternalDoc),			"SPECFAKTURYWEW",		DATATYPE_INVS,			CFGID_SPECFAKWEW,				RUNTIME_CLASS(CInvoiceDetailsOptionsDlg),	RUNTIME_CLASS(CCowDrwDocView), true},
	{ID_DOC_SPECFAKZEW,					IDS_DOCNAME_SPECFAKZEW,				RUNTIME_CLASS(CInvoiceDetailsExternalDoc),			"SPECFAKTURYZEW",		DATATYPE_INVS,			CFGID_SPECFAKZEW,				RUNTIME_CLASS(CInvoiceDetailsOptionsDlg),	RUNTIME_CLASS(CCowDrwDocView), true},
	{ID_DOC_PASS,						IDS_DOCNAME_PASS,					RUNTIME_CLASS(CPassPrintDoc),						"PASS",					DATATYPE_COWS,			CFGID_PASS,						NULL,										RUNTIME_CLASS(CCowDrwDocView), false},
	{ID_DOC_DEZYNFPZ,					IDS_DOCNAME_DEZYNFPZ,				RUNTIME_CLASS(CDezynfekcjaDoc),						"DEZYNF",				DATATYPE_INDOCS,		CFGID_DEZYNFPZ,					RUNTIME_CLASS(CDezynfDocOptDlg),			RUNTIME_CLASS(CCowDrwDocView), false},	
	{ID_DOC_DEZYNFWZ,					IDS_DOCNAME_DEZYNFWZ,				RUNTIME_CLASS(CDezynfekcjaDoc),						"DEZYNF",				DATATYPE_OUTDOCS,		CFGID_DEZYNFWZ,					RUNTIME_CLASS(CDezynfDocOptDlg),			RUNTIME_CLASS(CCowDrwDocView), false},
		
	{ID_DOC_BUYVATINVGRPWEIGHT,			IDS_DOCNAME_VATINVGRPWEIGHT,		RUNTIME_CLASS(CFakturaVATGroupWeightA4),			"FAKTURAVAT",			DATATYPE_BUYVATINVS,	CFGID_BUYFAKVATGRPWGHT,			RUNTIME_CLASS(CInvoiceDocOptionsDlg),		RUNTIME_CLASS(CCowDrwDocView), false}, 
	{ID_DOC_SELLVATINVGRPWEIGHT,		IDS_DOCNAME_VATINVGRPWEIGHT,		RUNTIME_CLASS(CFakturaVATGroupWeightA4),			"FAKTURAVAT",			DATATYPE_SELLVATINVS,	CFGID_SELLFAKVATGRPWGHT,		RUNTIME_CLASS(CInvoiceDocOptionsDlg),		RUNTIME_CLASS(CCowDrwDocView), false}, 

	{ID_DOC_SOKOLOW,					IDS_DOCNAME_SOKOLOW,				RUNTIME_CLASS(CSokolowDoc),							"SOKOLOW",				DATATYPE_COWS,			CFGID_SOKOLOW,					NULL,										RUNTIME_CLASS(CCowDrwDocView), false},

	{ID_DOC_PZZGL60DO,					IDS_DOCNAME_PZZGL60DO,				RUNTIME_CLASS(CZgloszenie60InDoc),					"ZPBOK_3_11",			DATATYPE_INDOCS,		CFGID_PZZGL60DO,				RUNTIME_CLASS(CZgloszenieOptDlg),			RUNTIME_CLASS(CCowDrwDocView),  true}, 
	{ID_DOC_WZZGL60Z,					IDS_DOCNAME_WZZGL60Z,				RUNTIME_CLASS(CZgloszenie60OutDoc),					"ZPBOK_3_11",			DATATYPE_OUTDOCS,		CFGID_WZZGL60Z,					RUNTIME_CLASS(CZgloszenieOptDlg),			RUNTIME_CLASS(CCowDrwDocView),  true}, 
	{ID_DOC_PZZGL30DO,					IDS_DOCNAME_PZZGL30DO,				RUNTIME_CLASS(CZgloszenie30InDoc),					"ZPBOK_4_11",			DATATYPE_INDOCS,		CFGID_PZZGL30DO,				RUNTIME_CLASS(CZgloszenieOptDlg),			RUNTIME_CLASS(CCowDrwDocView),  true}, 
	{ID_DOC_WZZGL30Z,					IDS_DOCNAME_WZZGL30Z,				RUNTIME_CLASS(CZgloszenie30OutDoc),					"ZPBOK_4_11",			DATATYPE_OUTDOCS,		CFGID_WZZGL30Z,					RUNTIME_CLASS(CZgloszenieOptDlg),			RUNTIME_CLASS(CCowDrwDocView),  true}, 
	{ID_DOC_PZZGLPOCZTDO,				IDS_DOCNAME_PZZGLPOCZTDO,			RUNTIME_CLASS(CZgloszenieCardInDoc),				"ZPBOK_1_11",			DATATYPE_INDOCS,		CFGID_PZZGLPOCZTDO,				RUNTIME_CLASS(CZgloszenieOptDlg),			RUNTIME_CLASS(CCowDrwDocView),  true}, 
	{ID_DOC_WZZGLPOCZTZ,				IDS_DOCNAME_WZZGLPOCZTZ,			RUNTIME_CLASS(CZgloszenieCardOutDoc),				"ZPBOK_1_11",			DATATYPE_OUTDOCS,		CFGID_WZZGLPOCZTZ,				RUNTIME_CLASS(CZgloszenieOptDlg),			RUNTIME_CLASS(CCowDrwDocView),  true}, 

	{ID_DOC_BUYINVZGL60DO,				IDS_DOCNAME_PZZGL60DO,				RUNTIME_CLASS(CZgloszenie60BuyInv),					"ZPBOK_3_11",			DATATYPE_BUYINVS,		CFGID_BUYINVZGL60DO,			RUNTIME_CLASS(CZgloszenieOptDlg),			RUNTIME_CLASS(CCowDrwDocView),  true}, 
	{ID_DOC_BUYINVZGL30DO,				IDS_DOCNAME_PZZGL30DO,				RUNTIME_CLASS(CZgloszenie30BuyInv),					"ZPBOK_4_11",			DATATYPE_BUYINVS,		CFGID_BUYINVZGL30DO,			RUNTIME_CLASS(CZgloszenieOptDlg),			RUNTIME_CLASS(CCowDrwDocView),  true},
	{ID_DOC_BUYINVZGLPOCZTDO,			IDS_DOCNAME_PZZGLPOCZTDO,			RUNTIME_CLASS(CZgloszenieCardBuyInv),				"ZPBOK_1_11",			DATATYPE_BUYINVS,		CFGID_BUYINVZGLPOCZTDO,			RUNTIME_CLASS(CZgloszenieOptDlg),			RUNTIME_CLASS(CCowDrwDocView),  true}, 
	{ID_DOC_SELLINVZGL60DO,				IDS_DOCNAME_WZZGL60Z,				RUNTIME_CLASS(CZgloszenie60SellInv),				"ZPBOK_3_11",			DATATYPE_SELLINVS,		CFGID_SELLINVZGL60Z,			RUNTIME_CLASS(CZgloszenieOptDlg),			RUNTIME_CLASS(CCowDrwDocView),  true},
	{ID_DOC_SELLINVZGL30DO,				IDS_DOCNAME_WZZGL30Z,				RUNTIME_CLASS(CZgloszenie30SellInv),				"ZPBOK_4_11",			DATATYPE_SELLINVS,		CFGID_SELLINVZGL30Z,			RUNTIME_CLASS(CZgloszenieOptDlg),			RUNTIME_CLASS(CCowDrwDocView),  true},	
	{ID_DOC_SELLINVZGLPOCZTDO,			IDS_DOCNAME_WZZGLPOCZTZ,			RUNTIME_CLASS(CZgloszenieCardSellInv),				"ZPBOK_1_11",			DATATYPE_SELLINVS,		CFGID_SELLINVZGLPOCZTZ,			RUNTIME_CLASS(CZgloszenieOptDlg),			RUNTIME_CLASS(CCowDrwDocView),  true},	
	
	{ID_DOC_OSWIAD_FPMW,				IDS_DOCNAME_OSWIAD_FPMW,			RUNTIME_CLASS(COswiadczenieFPWMDoc),				"OSWIADCZENIEFPMW",		DATATYPE_VATINVS,		CFGID_OSWIADFPWM,				NULL,										RUNTIME_CLASS(CCowDrwDocView), false},	
	{ID_DOC_FAKRR_WEIGHT,				IDS_DOCNAME_FAKRR_WEIGHT,			RUNTIME_CLASS(CFakturaRRA4),						"FAKTURARR",			DATATYPE_RRINVS,		CFGID_FAKRRWEIGHT,				RUNTIME_CLASS(CInvoiceDocOptionsDlg),		RUNTIME_CLASS(CCowDrwDocView), true}, 
	{ID_DOC_FAKRR3_WEIGHT,				IDS_DOCNAME_FAKRR3_WEIGHT,			RUNTIME_CLASS(CFakturaRRA5),						"FAKTURARRA5",			DATATYPE_RRINVS,		CFGID_FAKRR3WEIGHT,				RUNTIME_CLASS(CInvoiceDocOptionsDlg),		RUNTIME_CLASS(CCowDrwDocView), true}, 
	{ID_DOC_FAKRR_PIECE,				IDS_DOCNAME_FAKRR_PIECE,			RUNTIME_CLASS(CFakturaRRA4Piece),					"FAKTURARR",			DATATYPE_RRINVS,		CFGID_FAKRRPIECE,				RUNTIME_CLASS(CInvoiceDocOptionsDlg),		RUNTIME_CLASS(CCowDrwDocView), true}, 
	{ID_DOC_FAKRR3_PIECE,				IDS_DOCNAME_FAKRR3_PIECE,			RUNTIME_CLASS(CFakturaRRA5Piece),					"FAKTURARRA5",			DATATYPE_RRINVS,		CFGID_FAKRR3PIECE,				RUNTIME_CLASS(CInvoiceDocOptionsDlg),		RUNTIME_CLASS(CCowDrwDocView), true}, 	
	{ID_DOC_EXPENSESSUMMARY,			IDS_DOCNAME_EXPENSESSUM,			RUNTIME_CLASS(CExpensesSummaryDoc),					"KOSZTY",				DATATYPE_EXPENSES,		CFGID_EXPENSESSUM,				NULL,										RUNTIME_CLASS(CCowDrwDocView), false},
	//{ID_DOC_IDPZBARCODES,				IDS_DOCNAME_IDPZBARCODES,			RUNTIME_CLASS(CBarcodesCowTransInfoDoc),			"IDPZBC",				DATATYPE_OUTDOCS,		CFGID_IDPZBC,					NULL,										RUNTIME_CLASS(CCowDrwDocView), true}, 
	{ID_DOC_FAKRRTERM3_WEIGHT,			IDS_DOCNAME_FAKRRTERM3_WEIGHT,		RUNTIME_CLASS(CFakturaRRA5),						"FAKTURARRTERM",		DATATYPE_RRINVS,		CFGID_FAKRRTERM3WEIGHT,			RUNTIME_CLASS(CInvoiceDocOptionsDlg),		RUNTIME_CLASS(CCowDrwDocView), true},
	{ID_DOC_FAKRRTERM3_PIECE,			IDS_DOCNAME_FAKRRTERM3_PIECE,		RUNTIME_CLASS(CFakturaRRA5Piece),					"FAKTURARRTERM",		DATATYPE_RRINVS,		CFGID_FAKRRTERM3PIECE,			RUNTIME_CLASS(CInvoiceDocOptionsDlg),		RUNTIME_CLASS(CCowDrwDocView), true}, 	
	{ID_DOC_INTRANSPORTDOC,				IDS_DOCNAME_INTRANSPORTDOC,			RUNTIME_CLASS(CPzTransportDoc),						"TRANSPORTOWKA",		DATATYPE_INDOCS,		CFGID_TRANSPORTINDOC,			RUNTIME_CLASS(CTransportDocOptDlg),			RUNTIME_CLASS(CCowDrwDocView), true},
	{ID_DOC_OUTTRANSPORTDOC,			IDS_DOCNAME_OUTTRANSPORTDOC,		RUNTIME_CLASS(CWzTransportDoc),						"TRANSPORTOWKA",		DATATYPE_OUTDOCS,		CFGID_TRANSPORTOUTDOC,			RUNTIME_CLASS(CTransportDocOptDlg),			RUNTIME_CLASS(CCowDrwDocView), true},
	{ID_DOC_KSIEGASTADA,				IDS_DOCNAME_KSIEGASTADA,			RUNTIME_CLASS(CKsiegaStada),						"KSIEGASTADA",			DATATYPE_COWS,			CFGID_KSIEGASTADA,				RUNTIME_CLASS(CHerdBookOptDlg),				RUNTIME_CLASS(CCowDrwDocView), true}, 

	{ID_DOC_BUYVATINVGRPPRICEPIECE,		IDS_DOCNAME_VATINVGRPPRICEPIECE,	RUNTIME_CLASS(CFakturaVATGroupPricePerKgPieceA4),	"FAKTURAVAT",			DATATYPE_BUYVATINVS,	CFGID_BUYINVVATGRPPRICEPIECE,	RUNTIME_CLASS(CInvoiceDocOptionsDlg),		RUNTIME_CLASS(CCowDrwDocView), false}, 
	{ID_DOC_SELLVATINVGRPPRICEPIECE,	IDS_DOCNAME_VATINVGRPPRICEPIECE,	RUNTIME_CLASS(CFakturaVATGroupPricePerKgPieceA4),	"FAKTURAVAT",			DATATYPE_SELLVATINVS,	CFGID_SELLINVVATGRPPRICEPIECE,	RUNTIME_CLASS(CInvoiceDocOptionsDlg),		RUNTIME_CLASS(CCowDrwDocView), false}, 

	{ID_DOC_WEIGHTINGINDOC,				IDS_DOCNAME_WEIGHTINGDOC,			RUNTIME_CLASS(CWeightingInDoc),						"WAZENIE",				DATATYPE_INDOCS,		CFGID_WEIGHTINGINDOC,			NULL,										RUNTIME_CLASS(CCowDrwDocView), true},
	{ID_DOC_WEIGHTINGOUTDOC,			IDS_DOCNAME_WEIGHTINGDOC,			RUNTIME_CLASS(CWeightingOutDoc),					"WAZENIE",				DATATYPE_OUTDOCS,		CFGID_WEIGHTINGOUTDOC,			NULL,										RUNTIME_CLASS(CCowDrwDocView), true},
	
	{ID_DOC_BUYVATINVGRPPRICEWEIGHT,	IDS_DOCNAME_VATINVGRPPRICEWEIGHT,	RUNTIME_CLASS(CFakturaVATGroupPricePerKgWeightA4),	"FAKTURAVAT",			DATATYPE_BUYVATINVS,	CFGID_BUYINVVATGRPPRICEWEIGHT,	RUNTIME_CLASS(CInvoiceDocOptionsDlg),		RUNTIME_CLASS(CCowDrwDocView), false}, 
	{ID_DOC_SELLVATINVGRPPRICEWEIGHT,	IDS_DOCNAME_VATINVGRPPRICEWEIGHT,	RUNTIME_CLASS(CFakturaVATGroupPricePerKgWeightA4),	"FAKTURAVAT",			DATATYPE_SELLVATINVS,	CFGID_SELLINVVATGRPPRICEWEIGHT,	RUNTIME_CLASS(CInvoiceDocOptionsDlg),		RUNTIME_CLASS(CCowDrwDocView), false}, 

	{ID_DOC_NORMALIZEFOODCHAINRRINV,	IDS_DOCNAME_NORMALIZEFOODCHAIN,		RUNTIME_CLASS(CNormalizeFoodChain),					"LANCUCH_ZYW",			DATATYPE_RRINVS,		CFGID_NORMALIZEFOODCHAINRRINV,	NULL,										RUNTIME_CLASS(CCowDrwDocView), false}, 

	{ID_DOC_REGISTRATION,				IDS_DOCNAME_REGISTRACTION,			RUNTIME_CLASS(RegistrationDuplex),						"ZBR_2_10",			DATATYPE_INDOCS,		CFGID_REGISTRACTION,				NULL,			RUNTIME_CLASS(CCowDrwDocView),  true}, 

	{NULL_DOC_ID,						0,									NULL,												"",						0,						0,								NULL,										NULL,						   false}



};
