#ifndef __PRINTDOCS_H__
#define __PRINTDOCS_H__


typedef struct tagPRINTDOCS
{
	UINT nID;
	UINT nResDocName;
	CRuntimeClass *pDocClass;
	char szDocTemplateName[MAX_PATH];
	UINT iDataType;
	UINT iCfgItemId;	
	CRuntimeClass *pDocOptDlgClass;
	CRuntimeClass *pDocViewClass;
	bool bSortCow;
} PRINTDOCS;


#define ID_DOC_BASE (WM_APP+1001)
#define NULL_DOC_ID 0

extern const  PRINTDOCS g_PrintDocs[];

#define ID_DOC_WETBOOK					ID_DOC_BASE+1
#define ID_DOC_INDOCS					ID_DOC_BASE+2
#define ID_DOC_OUTDOCS					ID_DOC_BASE+3
#define ID_DOC_RAPORT					ID_DOC_BASE+6

#define ID_DOC_PZZGL60DO				ID_DOC_BASE+26
#define ID_DOC_PZZGL30DO				ID_DOC_BASE+7
#define ID_DOC_PZZGLPOCZTDO				ID_DOC_BASE+9

#define ID_DOC_WZZGL60Z					ID_DOC_BASE+27
#define ID_DOC_WZZGL30Z					ID_DOC_BASE+8
#define ID_DOC_WZZGLPOCZTZ				ID_DOC_BASE+10

#define ID_DOC_BUYINVZGL60DO			ID_DOC_BASE+4
#define ID_DOC_BUYINVZGL30DO			ID_DOC_BASE+5
#define ID_DOC_BUYINVZGLPOCZTDO			ID_DOC_BASE+30

#define ID_DOC_SELLINVZGL60DO			ID_DOC_BASE+31
#define ID_DOC_SELLINVZGL30DO  			ID_DOC_BASE+11
#define ID_DOC_SELLINVZGLPOCZTDO		ID_DOC_BASE+12


#define ID_DOC_BUYVATINVOICE			ID_DOC_BASE+13
#define ID_DOC_BUYVATINVGRPPIECE		ID_DOC_BASE+14
#define ID_DOC_SWIADZDR					ID_DOC_BASE+15
#define ID_DOC_PRZELEW					ID_DOC_BASE+16
#define ID_DOC_ZBRPOLPRZEL				ID_DOC_BASE+17
#define ID_DOC_ZESTFAKKUPNA				ID_DOC_BASE+18
#define ID_DOC_ZESTFAKSPRZ				ID_DOC_BASE+19
#define ID_DOC_IDPZ						ID_DOC_BASE+20
#define ID_DOC_BUYVATINVCOMPACTPIECE	ID_DOC_BASE+21
#define ID_DOC_SPECFAKWEW				ID_DOC_BASE+22
#define ID_DOC_PASS						ID_DOC_BASE+23
#define ID_DOC_DEZYNFWZ					ID_DOC_BASE+24
#define ID_DOC_DEZYNFPZ					ID_DOC_BASE+25
#define ID_DOC_BUYVATINVGRPWEIGHT		ID_DOC_BASE+28
#define ID_DOC_SOKOLOW					ID_DOC_BASE+29
#define ID_DOC_OSWIAD_FPMW				ID_DOC_BASE+32
#define ID_DOC_FAKRR_PIECE				ID_DOC_BASE+33
#define ID_DOC_FAKRR3_PIECE				ID_DOC_BASE+34
#define ID_DOC_EXPENSESSUMMARY			ID_DOC_BASE+35
#define ID_DOC_IDPZBARCODES				ID_DOC_BASE+36
#define ID_DOC_HENTDYMOLABEL			ID_DOC_BASE+37
#define ID_DOC_FAKRRTERM3_PIECE			ID_DOC_BASE+38
#define ID_DOC_FAKRRTERM3_WEIGHT		ID_DOC_BASE+39
#define ID_DOC_INDOCHENTDYMOLABEL		ID_DOC_BASE+40
#define ID_DOC_OUTDOCHENTDYMOLABEL		ID_DOC_BASE+41
#define ID_DOC_INVHENTDYMOLABEL			ID_DOC_BASE+42
#define ID_DOC_INTRANSPORTDOC			ID_DOC_BASE+43
#define ID_DOC_OUTTRANSPORTDOC			ID_DOC_BASE+44
#define ID_DOC_KSIEGASTADA				ID_DOC_BASE+45
#define ID_DOC_SPECFAKZEW				ID_DOC_BASE+46
#define ID_DOC_BUYVATINVCOMPACTWEIGHT	ID_DOC_BASE+47
#define ID_DOC_FAKRR_WEIGHT  			ID_DOC_BASE+48
#define ID_DOC_FAKRR3_WEIGHT			ID_DOC_BASE+49

#define ID_DOC_SELLVATINVOICE			ID_DOC_BASE+50
#define ID_DOC_SELLVATINVGRPPIECE		ID_DOC_BASE+51
#define ID_DOC_SELLVATINVCOMPACTPIECE	ID_DOC_BASE+52
#define ID_DOC_SELLVATINVCOMPACTWEIGHT	ID_DOC_BASE+53
#define ID_DOC_SELLVATINVGRPWEIGHT		ID_DOC_BASE+54

#define ID_DOC_SELLVATINVGRPPRICEPIECE	ID_DOC_BASE+55
#define ID_DOC_BUYVATINVGRPPRICEPIECE   ID_DOC_BASE+56

#define ID_DOC_WEIGHTINGINDOC			ID_DOC_BASE+57
#define ID_DOC_WEIGHTINGOUTDOC			ID_DOC_BASE+58

#define ID_DOC_SELLVATINVGRPPRICEWEIGHT	ID_DOC_BASE+59
#define ID_DOC_BUYVATINVGRPPRICEWEIGHT	ID_DOC_BASE+60
#define ID_DOC_NORMALIZEFOODCHAINRRINV	ID_DOC_BASE+61

#define ID_DOC_REGISTRATION				ID_DOC_BASE+62

#define ID_PRINTDOC_FIRST ID_DOC_BASE 
#define ID_PRINTDOC_LAST ID_DOC_BASE+100

#endif
