#ifndef __REPOINVOICECOMPARATOR_H__
#define __REPOINVOICECOMPARATOR_H__

#include "../RepoInvoice.h"
#include "DataComparator.h"

enum REPOINVOICE_MEMBERS
{
	REPOINVOICE_MEMBER_INVOICEDATE  = 1,	
	REPOINVOICE_MEMBER_TRANSACTIONDATE,
    REPOINVOICE_MEMBER_TRANSACTIONPLACE,
    REPOINVOICE_MEMBER_VATRATE,
	REPOINVOICE_MEMBER_PAYWAY,
	REPOINVOICE_MEMBER_CUSTOMNUMBER,
	REPOINVOICE_MEMBER_PAYDUEDAYS,
	REPOINVOICE_MEMBER_INVOICEHENTALIAS,
	REPOINVOICE_MEMBER_COWCOUNT,
	REPOINVOICE_MEMBER_TOTALNET,
	REPOINVOICE_MEMBER_INVOICETYPE,
    REPOINVOICE_MEMBER_MAX
};

class RepoInvoiceComparator : public DataComparator<RepoInvoice>
{
public:
	virtual COMPARE_RESULT CompareBy(UINT dataMember,RepoInvoice* DataLeft,RepoInvoice* DataRight);
};


#endif