#ifndef __REPOHENTCOMPARATOR_H__
#define __REPOHENTCOMPARATOR_H__

#include "../RepoHent.h"
#include "DataComparator.h"

enum REPOHENT_MEMBERS
{
	REPOHENT_MEMBER_NAME  = 1,	
	REPOHENT_MEMBER_ALIAS,
    REPOHENT_MEMBER_STREET,
    REPOHENT_MEMBER_POBOX,
    REPOHENT_MEMBER_CITY,
    REPOHENT_MEMBER_ZIP,
	REPOHENT_MEMBER_PHONE,
	REPOHENT_MEMBER_NIP,
	REPOHENT_MEMBER_FARMNO,
	REPOHENT_MEMBER_WETNO,
	REPOHENT_MEMBER_EXTRAS,
	REPOHENT_MEMBER_PLATE,
	REPOHENT_MEMBER_HENTTYPE,
	REPOHENT_MEMBER_PESEL,
	REPOHENT_MEMBER_REGON,
	REPOHENT_MEMBER_IDNO,
	REPOHENT_MEMBER_ISSUEDATE,
	REPOHENT_MEMBER_ISSUEPOST,
	REPOHENT_MEMBER_ACCOUNTNO,
	REPOHENT_MEMBER_BANKNAME,
	REPOHENT_MEMBER_WETLICENCENO,
	REPOHENT_MEMBER_CELLPHONENO,
	REPOHENT_MEMBER_EMAILADDRESS,
	REPOHENT_MEMBER_LATITUDE,
	REPOHENT_MEMBER_LONGITUDE,

	REPOHENT_MEMBER_MAX
	
};


class RepoHentComparator : public DataComparator<RepoHent>
{
public:
	virtual COMPARE_RESULT CompareBy(UINT dataMember,RepoHent* DataLeft,RepoHent* DataRight);
};


#endif